#
# \brief  Download and prepare the Codezero kernel
# \author Norman Feske
# \date   2011-08-05
#

VERBOSE ?= @
ECHO    := @echo

#
# Print help information by default
#
help::

prepare:
	$(VERBOSE)../../tool/ports/prepare_port codezero

help::
	$(ECHO)
	$(ECHO) "Prepare the codezero base repository"
	$(ECHO)
	$(ECHO) "--- available commands ---"
	$(ECHO) "prepare - checkout upstream source codes"
	$(ECHO) "clean   - remove upstream source codes"
	$(ECHO)
