/**
 * Private libpng configuration
 */

#ifndef _INCLUDE__LIBPNG__PNGUSR_H_
#define _INCLUDE__LIBPNG__PNGUSR_H_

//#define PNG_NO_READ_SUPPORTED
//#define PNG_NO_WRITE_SUPPORTED
#define PNG_NO_READ_tIME
#define PNG_NO_WRITE_tIME
#define PNG_NO_MNG_FEATURES
#define PNG_NO_STDIO
#define PNG_NO_SETJMP_SUPPORTED
#define PNG_NO_FLOATING_POINT_SUPPORTED
#define PNG_NO_READ_tIME
#define PNG_NO_ASSEMBLER_CODE

#endif /* _INCLUDE__LIBPNG__PNGUSR_H_ */
