/* This file generated by gen-fib.c - DO NOT EDIT. */

#include "gmp.h"
#include "gmp-impl.h"

#if GMP_NUMB_BITS != 32
Error, error, this data is for 32 bits
#endif

const mp_limb_t
__gmp_fib_table[FIB_TABLE_LIMIT+2] = {
  CNST_LIMB (0x1),  /* -1 */
  CNST_LIMB (0x0),  /* 0 */
  CNST_LIMB (0x1),  /* 1 */
  CNST_LIMB (0x1),  /* 2 */
  CNST_LIMB (0x2),  /* 3 */
  CNST_LIMB (0x3),  /* 4 */
  CNST_LIMB (0x5),  /* 5 */
  CNST_LIMB (0x8),  /* 6 */
  CNST_LIMB (0xd),  /* 7 */
  CNST_LIMB (0x15),  /* 8 */
  CNST_LIMB (0x22),  /* 9 */
  CNST_LIMB (0x37),  /* 10 */
  CNST_LIMB (0x59),  /* 11 */
  CNST_LIMB (0x90),  /* 12 */
  CNST_LIMB (0xe9),  /* 13 */
  CNST_LIMB (0x179),  /* 14 */
  CNST_LIMB (0x262),  /* 15 */
  CNST_LIMB (0x3db),  /* 16 */
  CNST_LIMB (0x63d),  /* 17 */
  CNST_LIMB (0xa18),  /* 18 */
  CNST_LIMB (0x1055),  /* 19 */
  CNST_LIMB (0x1a6d),  /* 20 */
  CNST_LIMB (0x2ac2),  /* 21 */
  CNST_LIMB (0x452f),  /* 22 */
  CNST_LIMB (0x6ff1),  /* 23 */
  CNST_LIMB (0xb520),  /* 24 */
  CNST_LIMB (0x12511),  /* 25 */
  CNST_LIMB (0x1da31),  /* 26 */
  CNST_LIMB (0x2ff42),  /* 27 */
  CNST_LIMB (0x4d973),  /* 28 */
  CNST_LIMB (0x7d8b5),  /* 29 */
  CNST_LIMB (0xcb228),  /* 30 */
  CNST_LIMB (0x148add),  /* 31 */
  CNST_LIMB (0x213d05),  /* 32 */
  CNST_LIMB (0x35c7e2),  /* 33 */
  CNST_LIMB (0x5704e7),  /* 34 */
  CNST_LIMB (0x8cccc9),  /* 35 */
  CNST_LIMB (0xe3d1b0),  /* 36 */
  CNST_LIMB (0x1709e79),  /* 37 */
  CNST_LIMB (0x2547029),  /* 38 */
  CNST_LIMB (0x3c50ea2),  /* 39 */
  CNST_LIMB (0x6197ecb),  /* 40 */
  CNST_LIMB (0x9de8d6d),  /* 41 */
  CNST_LIMB (0xff80c38),  /* 42 */
  CNST_LIMB (0x19d699a5),  /* 43 */
  CNST_LIMB (0x29cea5dd),  /* 44 */
  CNST_LIMB (0x43a53f82),  /* 45 */
  CNST_LIMB (0x6d73e55f),  /* 46 */
  CNST_LIMB (0xb11924e1),  /* 47 */
};
