#
# \brief  Download, and unpack rumpkernel
# \author Josef Soentgen
# \date   2014-05-20
#

VERBOSE ?= @
ECHO    := @echo

#
# Print help information by default
#
help::

prepare:
	$(VERBOSE)../../tool/ports/prepare_port dde_rump

help::
	$(ECHO)
	$(ECHO) "Prepare the dde_rump repository"
	$(ECHO)
	$(ECHO) "--- available commands ---"
	$(ECHO) "prepare - checkout upstream source codes"
	$(ECHO)

