source ${genode_dir}/repos/libports/run/network_test_lwip.run
set test_result_lwip $test_result 

source ${genode_dir}/repos/libports/run/network_test_lwip_nic_bridge.run
set test_result_lwip_nic_bridge $test_result

source ${genode_dir}/repos/libports/run/network_test_libc_lwip.run
set test_result_libc_lwip $test_result

source ${genode_dir}/repos/libports/run/network_test_libc_lwip_nic_bridge.run
set test_result_libc_lwip_nic_bridge $test_result

puts "\nTest results:\n"
puts "lwip:                 $test_result_lwip"
puts "lwip_nic_bridge:      $test_result_lwip_nic_bridge"
puts "libc_lwip:            $test_result_libc_lwip"
puts "libc_lwip_nic_bridge: $test_result_libc_lwip_nic_bridge"
puts ""

puts "Test succeeded"
