#
# Build components
#

proc enable_test_1 { } { return 1 }
proc enable_test_2 { } { return 1 }
proc enable_test_3 { } { return 1 }
proc enable_test_4 { } { return 1 }
proc enable_test_5 { } { return 1 }
proc enable_test_6 { } { return 1 }
proc enable_test_7 { } { return 0 }

source ${genode_dir}/repos/libports/run/nic_router.inc

lappend targets server/dynamic_rom

build $targets

create_boot_directory


#
# Test 1 utilities
#

proc test_1_start_nodes { } { return "
[client_start       udp_client_1 udp 10.0.98.55 10.0.98.33 255.255.255.0 nic_router 1337 10.0.98.33]
[client_start lan_1_udp_client_1 udp 10.0.99.56 10.0.99.33 255.255.255.0 nic_router 1337 10.0.99.55]
[server_start lan_1_udp_server_1 udp 10.0.99.55 10.0.99.33 255.255.255.0 nic_router 1337 ]" }

proc test_1_router_config { } { return {|
      |   + policy | label_prefix: udp_client_1 | domain: udp_client_1
      |   + policy | label_prefix: lan_1 | domain: lan_1
      |   + domain udp_client_1 | interface: 10.0.98.33/24
      |     + udp-forward | port: 1337 | domain: lan_1 | to: 10.0.99.55
      |   + domain lan_1 | interface: 10.0.99.33/24} }


#
# Test 2 utilities
#

proc test_2_start_nodes { } { return "
[client_start udp_client_2 udp 10.0.2.212  10.0.2.1    255.255.255.0 nic_bridge 1 10.0.2.55]
[server_start udp_server_2 udp 18.17.16.15 18.17.16.14 255.255.0.0   nic_router 1 ]" }

proc test_2_router_config { } { return {|
      |   + policy | label_prefix: udp_server_2 | domain: udp_server_2
      |   + domain udp_server_2 | interface: 18.17.16.14/24} }


#
# Test 3 utilities
#

proc test_3_start_nodes { } { return "
[client_start udp_client_3 udp 217.13.192.2 217.13.192.1 255.255.192.0 nic_router 65535 10.0.2.213]
[server_start udp_server_3 udp 10.0.2.213   10.0.2.55    255.255.255.0 nic_bridge 65535 ]" }

proc test_3_router_config { } { return {|
      |   + policy | label_prefix: udp_client_3 | domain: udp_client_3
      |   + domain udp_client_3 | interface: 217.13.192.1/24
      |     + ip | dst: 10.0.2.0/24 | domain: uplink} }


#
# Test 4 utilities
#

proc test_4_start_nodes { } { return "
[client_start http_client_1 http 10.0.2.201   10.0.2.1    255.255.255.0 nic_bridge 80 10.0.2.55]
[server_start http_server_1 http 192.168.1.18 192.168.1.1 255.255.255.0 nic_router 80 ]" }

proc test_4_router_config { } { return {|
      |   + policy | label_prefix: http_server_1 | domain: http_server_1
      |   + domain http_server_1 | interface: 192.168.1.1/24} }


#
# Test 5 utilities
#

proc test_5_start_nodes { } { return "
[client_start http_client_2 http 10.0.2.202   10.0.2.1    255.255.255.0 nic_bridge 8080 10.0.2.55]
[server_start http_server_2 http 192.168.2.72 192.168.2.1 255.255.255.0 nic_router 8080 ]" }

proc test_5_router_config { } { return {|
      |   + policy | label_prefix: http_server_2 | domain: http_server_2
      |   + domain http_server_2 | interface: 192.168.2.1/24} }


#
# Test 6 utilities
#

proc test_6_start_nodes { } { return "
[client_start http_client_3 http 100.200.0.128 100.200.0.1 255.255.0.0   nic_router 2345 10.0.2.203]
[server_start http_server_3 http 10.0.2.203    10.0.2.1    255.255.255.0 nic_bridge 2345 ]" }

proc test_6_router_config { } { return {|
      |   + policy | label_prefix: http_client_3 | domain: http_client_3
      |   + domain http_client_3 | interface: 100.200.0.1/24
      |     + tcp | dst: 10.0.0.0/16 | + permit | port: 2345 | domain: uplink} }


#
# Test 7 utilities
#

proc test_7_start_nodes { } { return "
[client_start lan_2_client_1 http dhcp       dhcp     dhcp   nic_router 2345 10.0.2.204]
[client_start lan_2_client_2 http dhcp       dhcp     dhcp   nic_router 3456 10.0.2.240]
[client_start lan_2_client_3 http dhcp       dhcp     dhcp   nic_router 3456 10.0.2.240]
[server_start lan_3_server_1 http 10.0.2.204 10.0.2.1 255.255.255.0 nic_router 2345 ]
[server_start lan_3_server_2 http 10.0.2.240 10.0.2.1 255.255.255.0 nic_router 3456 ]" }

proc test_7_router_config { } { return {|
      |   + policy | label_prefix: lan_2 | domain: lan_2
      |   + policy | label_prefix: lan_3 | domain: lan_3
      |   + domain lan_2 | interface: 100.200.0.1/24
      |     + dhcp-server | ip_first:          100.200.0.32
      |     |             | ip_last:           100.200.0.64
      |     |             | ip_lease_time_sec: 3600
      |     | + dns-server | ip: 8.8.8.8
      |     + tcp | dst: 10.0.0.0/16
      |       + permit | port: 2345 | domain: lan_3
      |       + permit | port: 3456 | domain: lan_3
      |   + domain lan_3 | interface: 10.0.2.1/24
      |     + nat | domain: lan_2 | tcp-ports: 18} }


for { set i 1 } { $i <= 7 } { incr i } {
	if {![enable_test_$i]} {
		proc test_${i}_start_nodes   { } { }
		proc test_${i}_router_config { } { }
	}
}


#
# Init config
#

install_config {
config | prio_levels: 2
+ parent-provides
  + service ROM
  + service IRQ
  + service IO_MEM
  + service IO_PORT
  + service PD
  + service RM
  + service CPU
  + service LOG

+ default-route
  + any-service
    + parent
    + any-child

+ default | caps: 100 | ram: 1M

+ start timer | priority: 0
  + provides | + service Timer

+ start nic_loopback | priority: -1
  + provides | + service Nic

+ start dynamic_rom | ram: 4M
  + provides | + service ROM
  + config | verbose: yes
    + rom nic_router.config
      + inline
      | + config
      |   |      verbose:                   no
      |   |      verbose_packets:           no
      |   |      verbose_domain_state:      no
      |   |      dhcp_discover_timeout_sec: 3
      |   |      dhcp_request_timeout_sec:  3
      |   |      dhcp_offer_timeout_sec:    3
      |   |      udp_idle_timeout_sec:      30
      |   |      tcp_idle_timeout_sec:      30
      |   |      tcp_max_segm_lifetime_sec: 15
      |   |
      |   + report
      |   + nic-client | domain: uplink
      |   + domain uplink | interface: 10.0.2.55/24 | gateway: 10.0.2.1 | verbose_packets: no
      |   | + tcp-forward | port:   80 | domain: http_server_1 | to: 192.168.1.18
      |   | + tcp-forward | port: 8080 | domain: http_server_2 | to: 192.168.2.72
      |   | + udp-forward | port:    1 | domain: udp_server_2  | to: 18.17.16.15
      |   | + nat | domain: http_client_3 | tcp-ports: 6
      |   | + ip | dst: 217.13.192.0/24 | domain: udp_client_3
      |   |
      |   } [test_2_router_config] {
      |   } [test_3_router_config] {
      |   } [test_4_router_config] {
      |   } [test_6_router_config] {
      |   } [test_7_router_config] {
      |
      + sleep | milliseconds: 4000
      + inline
      | + config
      |   |      verbose:                   no
      |   |      verbose_packets:           no
      |   |      verbose_domain_state:      no
      |   |      dhcp_discover_timeout_sec: 3
      |   |      dhcp_request_timeout_sec:  3
      |   |      dhcp_offer_timeout_sec:    3
      |   |      udp_idle_timeout_sec:      30
      |   |      tcp_idle_timeout_sec:      30
      |   |      tcp_max_segm_lifetime_sec: 15
      |   |
      |   + nic-client | domain: uplink
      |   + domain uplink | interface: 10.0.2.55/24 | gateway: 10.0.2.1 | verbose_packets: no
      |   | + tcp-forward | port:   80 | domain: http_server_1 | to: 192.168.1.18
      |   | + tcp-forward | port: 8080 | domain: http_server_2 | to: 192.168.2.72
      |   | + udp-forward | port:    1 | domain: udp_server_2  | to: 18.17.16.15
      |   | + nat | domain: http_client_3 | tcp-ports: 6
      |   | + ip | dst: 217.13.192.0/24 | domain: udp_client_3
      |   |
      |   } [test_1_router_config] {
      |   } [test_2_router_config] {
      |   } [test_3_router_config] {
      |   } [test_4_router_config] {
      |   } [test_5_router_config] {
      |   } [test_6_router_config] {
      |   } [test_7_router_config] {
      |
      + sleep | milliseconds: 6000
      + inline
      | + config
      |   |      verbose:                   no
      |   |      verbose_packets:           no
      |   |      verbose_domain_state:      no
      |   |      dhcp_discover_timeout_sec: 3
      |   |      dhcp_request_timeout_sec:  3
      |   |      dhcp_offer_timeout_sec:    3
      |   |      udp_idle_timeout_sec:      30
      |   |      tcp_idle_timeout_sec:      30
      |   |      tcp_max_segm_lifetime_sec: 15
      |   |
      |   + report | interval_sec: 2 | bytes: yes | config: no
      |   + nic-client | domain: uplink
      |   + domain uplink | interface: 10.0.2.55/24 | gateway: 10.0.2.1 | verbose_packets: no
      |     + tcp-forward | port:   80 | domain: http_server_1 | to: 192.168.1.18
      |     + tcp-forward | port: 8080 | domain: http_server_2 | to: 192.168.2.72
      |     + udp-forward | port:    1 | domain: udp_server_2  | to: 18.17.16.15
      |     + nat | domain: http_client_3 | tcp-ports: 6
      |     + ip | dst: 217.13.192.0/24 | domain: udp_client_3
      |
      + sleep | milliseconds: 500
      + inline
      | + config
      |   |      verbose:                   no
      |   |      verbose_packets:           no
      |   |      verbose_domain_state:      no
      |   |      dhcp_discover_timeout_sec: 3
      |   |      dhcp_request_timeout_sec:  3
      |   |      dhcp_offer_timeout_sec:    3
      |   |      udp_idle_timeout_sec:      30
      |   |      tcp_idle_timeout_sec:      30
      |   |      tcp_max_segm_lifetime_sec: 15
      |   |
      |   + report | interval_sec: 2 | bytes: yes | config: no
      |   + nic-client | domain: uplink
      |   + domain uplink | interface: 10.0.2.55/24 | gateway: 10.0.2.1 | verbose_packets: no
      |   | + tcp-forward | port:   80 | domain: http_server_1 | to: 192.168.1.18
      |   | + tcp-forward | port: 8080 | domain: http_server_2 | to: 192.168.2.72
      |   | + udp-forward | port:    1 | domain: udp_server_2  | to: 18.17.16.15
      |   | + nat | domain: http_client_3 | tcp-ports: 6
      |   | + ip | dst: 217.13.192.0/24 | domain: udp_client_3
      |   |
      |   } [test_1_router_config] {
      |   } [test_2_router_config] {
      |   } [test_3_router_config] {
      |   } [test_4_router_config] {
      |   } [test_5_router_config] {
      |   } [test_6_router_config] {
      |   } [test_7_router_config] {
      |
      + sleep | milliseconds: 3600000

+ start nic_router | caps: 200 | priority: -1 | ram: 10M
  + provides
    + service Nic
    + service Uplink
  + route
    + service ROM | label: config | + child dynamic_rom | label: nic_router.config
    + service Nic                 | + child nic_bridge
    + service Report              | + child report_rom
    + any-service
      + parent
      + any-child

+ start nic_bridge | caps: 200 | priority: -1 | ram: 10M
  + provides | + service Nic
  + config
    + policy | label_prefix: nic_router    | ip_addr: 10.0.2.55
    + policy | label_prefix: http_client_1 | ip_addr: 10.0.2.201
    + policy | label_prefix: http_client_2 | ip_addr: 10.0.2.202
    + policy | label_prefix: http_server_3 | ip_addr: 10.0.2.203
    + policy | label_prefix: udp_client_2  | ip_addr: 10.0.2.212
    + policy | label_prefix: udp_server_3  | ip_addr: 10.0.2.213
  + route
    + service Nic | + child nic_loopback
    + any-service
      + parent
      + any-child

+ start report_rom | ram: 1M
  + provides
    + service Report
    + service ROM
  + config | verbose: yes

} [test_1_start_nodes] {
} [test_2_start_nodes] {
} [test_3_start_nodes] {
} [test_4_start_nodes] {
} [test_5_start_nodes] {
} [test_6_start_nodes] {
} [test_7_start_nodes] {
-
}

build_boot_image [build_artifacts]

for {set i 0} {$i < $nr_of_clients} {incr i 1} {
	append done_string {.*Test done.*\n}
}

run_genode_until $done_string 240
