/* This file is automatically generated by gen-fac_ui.c */

#if GMP_NUMB_BITS != 32
Error , error this data is for 32 GMP_NUMB_BITS only
#endif
#if GMP_LIMB_BITS != 32
Error , error this data is for 32 GMP_LIMB_BITS only
#endif
/* This table is 0!,1!,2!,3!,...,n! where n! has <= GMP_NUMB_BITS bits */
#define ONE_LIMB_FACTORIAL_TABLE CNST_LIMB(0x1),CNST_LIMB(0x1),CNST_LIMB(0x2),CNST_LIMB(0x6),CNST_LIMB(0x18),CNST_LIMB(0x78),CNST_LIMB(0x2d0),CNST_LIMB(0x13b0),CNST_LIMB(0x9d80),CNST_LIMB(0x58980),CNST_LIMB(0x375f00),CNST_LIMB(0x2611500),CNST_LIMB(0x1c8cfc00)

/* is 2^(GMP_LIMB_BITS+1)/exp(1) */
#define FAC2OVERE CNST_LIMB(0xbc5c254b)

/* FACMULn is largest odd x such that x*(x+2)*...*(x+2(n-1))<=2^GMP_NUMB_BITS-1 */

#define FACMUL2 CNST_LIMB(0xffff)
#define FACMUL3 CNST_LIMB(0x657)
#define FACMUL4 CNST_LIMB(0xfd)
