#
# Windows 7 in VirtualBox 5
#

assert_spec x86
assert_spec nova

set flavor   "win7"
set vm_ram   "1280M"

set use_vbox5 1

set use_rumpfs 1
# Write overlay only into ram
set use_ram_fs 1
# However read initial overlay from disk
set use_overlay_from_disk 1

set use_serial 0

set use_usb 1
set use_ps2 [have_spec ps2]

set use_vms 1
set use_cpu_load 0

# use generic vbox5 VMM version
set use_vbox5_nova 0

source ${genode_dir}/repos/ports/run/vbox_win.inc
