#
# Windows 7 64bit in VirtualBox
#

assert_spec x86_64
assert_spec nova

set flavor   "win7_64_raw"
set vm_ram   "1280M"

set use_vbox5 1

# use vm image from a raw disk partition
set use_rumpfs 0
set use_ram_fs 0
set use_overlay_from_disk 0

set use_serial 0
set use_check_result 1

set use_usb [expr ![get_cmd_switch --autopilot]]
set use_ps2 1

set use_vms 1
set use_cpu_load 0

source ${genode_dir}/repos/ports/run/vbox_win.inc
