#
# Windows 10 in VirtualBox 5
#

assert {[have_spec nova]}
assert {[have_spec x86_64]}

set flavor   "win10_64"
set vm_ram   "8280M"

set use_vbox5 1

set use_rumpfs 1
# Write overlay only into ram
set use_ram_fs 1
# However read initial overlay from disk
set use_overlay_from_disk 1

set use_serial 0
set use_check_result 1

set use_usb [expr ![have_cmd_switch --autopilot]]
set use_ps2 1

set use_vms 1
set use_cpu_load 0

set use_webcam 1

source ${genode_dir}/repos/ports/run/vbox_win.inc
