#
# Ubuntu 16.04 64bit in VBox 5
#

assert_spec x86_64
assert_spec nova

set flavor   "ubuntu_16_04_64"
set vm_ram   "9460M"

set use_vbox5 1

set use_rumpfs 1
# Write overlay only into ram
set use_ram_fs 1
# However read initial overlay from disk
set use_overlay_from_disk 1

set use_serial 1
set use_check_result 1

set use_usb [expr ![get_cmd_switch --autopilot]]
set use_ps2 1

set use_vms 1
set use_cpu_load 1

source ${genode_dir}/repos/ports/run/vbox_win.inc
