#ifndef ____H_GENODEIMPL
#define ____H_GENODEIMPL

/* GuestControlSvc.h */

typedef struct { } VBOXGUESTCTRLHOSTCBCTX, *PVBOXGUESTCTRLHOSTCBCTX;
typedef struct { } VBOXGUESTCTRLHOSTCALLBACK, *PVBOXGUESTCTRLHOSTCALLBACK;
enum GUEST_FILE_SEEKTYPE { };

#endif // !____H_GENODEIMPL
