#
# \brief  Test using netperf with l4linux
# \date   2013-07-08
#

if {[is_qemu_available]} {
	puts "\nNetperf running on Qemu is not supported.\n"
	exit
}

#
# Remove when testing USB 3.0 on x86
#
assert_spec foc_arndale

# network configuration
set use_nic_bridge      0

set use_usb_11          "no"
set use_usb_20          "no"
set use_usb_30          "yes"

source ${genode_dir}/repos/ports-foc/run/l4linux_netperf.inc
