build { core init lib/ld test/cache }

create_boot_directory

install_config {
	<config>
		<parent-provides>
			<service name="LOG"/>
			<service name="CPU"/>
			<service name="PD"/>
			<service name="ROM"/>
			<service name="IO_MEM"/>
		</parent-provides>
		<default-route>
			<any-service> <parent/> </any-service>
		</default-route>
		<default caps="100"/>

		<start name="test-cache" ram="64M"/>
	</config> }

build_boot_image [build_artifacts]

run_genode_until "done.*\n" 300
