#
# \brief  Download, and unpack BSD kernel sources
# \author Josef Soentgen
# \date   2014-11-09
#

VERBOSE ?= @
ECHO    := @echo

#
# Print help information by default
#
help::

prepare:
	$(VERBOSE)../../tool/ports/prepare_port dde_bsd

help::
	$(ECHO)
	$(ECHO) "Prepare the dde_bsd repository"
	$(ECHO)
	$(ECHO) "--- available commands ---"
	$(ECHO) "prepare - checkout upstream source codes"
	$(ECHO)
