#
# \brief  Download, and unpack iPXE
# \author Josef Soentgen
# \date   2014-05-20
#

VERBOSE ?= @
ECHO    := @echo

#
# Print help information by default
#
help::

prepare:
	$(VERBOSE)../../tool/ports/prepare_port dde_ipxe

help::
	$(ECHO)
	$(ECHO) "Prepare the dde_ipxe repository"
	$(ECHO)
	$(ECHO) "--- available commands ---"
	$(ECHO) "prepare - checkout upstream source codes"
	$(ECHO)

