#!/bin/sh

# command line arguments are grouped:
#   general
#   QtCore
#   QtNetwork
#   QtGui
#   QtSql

../qt-everywhere-opensource-src-5.8.0/configure \
    -opensource \
    -confirm-license \
    -no-separate-debug-info \
    -no-sse3 \
    -no-ssse3 \
    -no-sse4.1 \
    -no-sse4.2 \
    -no-avx \
    -no-avx2 \
    -no-avx512 \
    -no-reduce-relocations \
    -no-pch \
    -no-use-gold-linker \
    -skip qttranslations \
    -make tools \
    -nomake examples \
    -no-dbus \
    -no-accessibility \
    -no-qml-debug \
    \
    -no-glib \
    -no-eventfd \
    -no-inotify \
    -no-iconv \
    -no-icu \
    -qt-pcre \
    -system-zlib \
    -no-feature-poll_ppoll \
    -no-feature-process \
    -no-feature-sharedmemory \
    -no-feature-systemsemaphore \
    -no-feature-threadsafe-cloexec \
    \
    -openssl-linked \
    -no-system-proxies \
    -no-feature-ipv6ifname \
    -no-feature-networkinterface \
    \
    -no-cups \
    -no-fontconfig \
    -system-freetype \
    -no-harfbuzz \
    -opengl desktop \
    -qpa minimal \
    -no-xcb \
    -system-libjpeg \
    -system-libpng \
    -no-feature-sessionmanager \
    \
    -qt-sqlite
