create_boot_directory
import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/pkg/[drivers_interactive_pkg] \
                  [depot_user]/src/dynamic_rom \
                  [depot_user]/src/report_rom \
                  [depot_user]/src/nitpicker \
                  [depot_user]/src/cpu_burner \
                  [depot_user]/src/cpu_load_display \
                  [depot_user]/src/trace_subject_reporter \
                  [depot_user]/src/init

install_config {
config | prio_levels: 2
+ parent-provides
  + service ROM
  + service IRQ
  + service IO_MEM
  + service IO_PORT
  + service PD
  + service RM
  + service CPU
  + service LOG
  + service TRACE

+ default-route
  + any-service
    + parent
    + any-child

+ default | caps: 100 | ram: 1M

+ start timer
  + provides | + service Timer

+ start drivers | caps: 1500 | ram: 64M | managing_system: yes
  + binary init
  + route
    + service ROM | label: config | + parent | label: drivers.config
    + service Timer               | + child timer
    + service Capture             | + child nitpicker
    + service Event               | + child nitpicker
    + any-service                 | + parent

+ start nitpicker
  + provides
    + service Gui
    + service Capture
    + service Event
  + config
    + capture
    + event
    + domain pointer | layer: 1 | label: no | content: client | origin: pointer
    + domain default | layer: 2 | label: no | content: client | hover: always
    + policy | label_prefix: pointer | domain: pointer
    + default-policy | domain: default

+ start pointer
  + route
    + service Gui | + child nitpicker
    + any-service
      + parent
      + any-child

+ start report_rom | ram: 4M
  + provides
    + service Report
    + service ROM
  + config
    + policy
             label:  cpu_load_display -> trace_subjects
             report: trace_subject_reporter -> trace_subjects

+ start trace_subject_reporter | ram: 6M
  + config | period_ms: 500
    + report | activity: yes | affinity: yes
  + route
    + service Report | + child report_rom
    + service TRACE  | + parent | label:
    + any-service
      + parent
      + any-child

+ start cpu_load_display | ram: 6M
  + route
    + service ROM | label: trace_subjects | + child report_rom
    + any-service
      + parent
      + any-child

+ start dynamic_rom | ram: 4M
  + provides | + service ROM
  + config | verbose: yes
    + rom cpu_burner1.config
      + inline | description: initial state | + config | percent: 5
      + sleep  | milliseconds: 5000
      + inline | description: 50%           | + config | percent: 50
      + sleep  | milliseconds: 5000
    + rom cpu_burner2.config
      + inline | description: initial state | + config | percent: 5
      + sleep  | milliseconds: 4800
      + inline | description: 100%          | + config | percent: 70
      + sleep  | milliseconds: 2700

+ start cpu_burner.1
  + binary cpu_burner
  + route
    + service ROM | label: config | + child dynamic_rom | label: cpu_burner1.config
    + any-service
      + parent
      + any-child

+ start cpu_burner.2
  + binary cpu_burner
  + route
    + service ROM | label: config | + child dynamic_rom | label: cpu_burner2.config
    + any-service
      + parent
      + any-child
-
}

build_boot_image [build_artifacts]

append qemu_args " -smp 4,cores=4 "
run_genode_until forever
