create_boot_directory

import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/pkg/[drivers_interactive_pkg] \
                  [depot_user]/src/init \
                  [depot_user]/src/report_rom \
                  [depot_user]/src/dynamic_rom \
                  [depot_user]/src/nitpicker \
                  [depot_user]/src/libc \
                  [depot_user]/src/libpng \
                  [depot_user]/src/zlib

install_config {
config
+ parent-provides
  + service ROM
  + service CPU
  + service PD
  + service RM
  + service LOG
  + service IRQ
  + service IO_MEM
  + service IO_PORT

+ default-route
  + any-service
    + parent
    + any-child

+ default | caps: 100 | ram: 1M

+ start timer
  + provides | + service Timer

+ start drivers | caps: 1500 | ram: 64M | managing_system: yes
  + binary init
  + route
    + service ROM | label: config | + parent | label: drivers.config
    + service Timer               | + child timer
    + service Capture             | + child nitpicker
    + service Event               | + child nitpicker
    + any-service                 | + parent

+ start report_rom | ram: 2M
  + provides
    + service ROM
    + service Report
  + config
    + policy | label: decorator -> pointer | report: nitpicker -> pointer

+ start nitpicker
  + provides
    + service Gui
    + service Capture
    + service Event
  + config
    + capture
    + event
    + report | pointer: yes
    + domain default | layer: 2 | content: client | label: no
    + default-policy | domain: default

+ start dynamic_rom | ram: 4M
  + provides | + service ROM
  + config | verbose: yes
    + rom window_layout
      + inline | description: initial state
      + sleep | milliseconds: 500
      + inline | description: open window 1
      | + window_layout
      |   + boundary | width: 1024 | height: 768
      |     + window | id: 1 | title: Genode Toolchain | focused: yes
      |              | xpos: 100 | ypos:  50 | width: 200 | height: 200
      + sleep | milliseconds: 1000
      + inline | description: open window 2 behind window 1
      | + window_layout
      |   + boundary | width: 1024 | height: 768
      |     + window | id: 1 | title: Genode Toolchain | focused: yes
      |              | xpos: 100 | ypos:  50 | width: 200 | height: 200
      |     + window | id: 2 | title: Arora (2)
      |              | xpos: 170 | ypos: 150 | width: 300 | height: 200
      + sleep | milliseconds: 1000
      + inline | description: open window 3 in front
      | + window_layout
      |   + boundary | width: 1024 | height: 768
      |     + window | id: 3 | title: Launchpad
      |              | xpos: 210 | ypos: 250 | width: 400 | height: 200
      |     + window | id: 1 | title: Genode Toolchain | focused: yes
      |              | xpos: 100 | ypos:  50 | width: 200 | height: 200
      |     + window | id: 2 | title:  Arora (2)
      |              | xpos: 170 | ypos: 150 | width: 300 | height: 200
      + sleep | milliseconds: 1000
      + inline | description: bring window 1 to front
      | + window_layout
      |   + boundary | width: 1024 | height: 768
      |     + window | id: 1 | title: Genode Toolchain | focused: yes
      |              | xpos: 100 | ypos:  50 | width: 200 | height: 200
      |     + window | id: 3 | title: Launchpad
      |              | xpos: 210 | ypos: 250 | width: 400 | height: 200
      |     + window | id: 2 | title: Arora (2)
      |              | xpos: 170 | ypos: 150 | width: 300 | height: 200
      + sleep | milliseconds: 1000
      + inline | description: change title of window 1
      | + window_layout
      |   + boundary | width: 1024 | height: 768
      |     + window | id: 1 | title: Genode Toolchain (running) | focused: yes
      |              | xpos: 100 | ypos:  50 | width: 200 | height: 200
      |     + window | id: 3 | title: Launchpad
      |              | xpos: 210 | ypos: 250 | width: 400 | height: 200
      |     + window | id: 2 | title: Arora (2)
      |              | xpos: 170 | ypos: 150 | width: 300 | height: 200
      + sleep | milliseconds: 1000
      + inline | description: change focus to window 3
      | + window_layout
      |   + boundary | width: 1024 | height: 768
      |     + window | id: 1 | title:  Genode Toolchain (running)
      |              | xpos: 100 | ypos:  50 | width: 200 | height: 200
      |     + window | id: 3 | title: Launchpad | focused: yes
      |              | xpos: 210 | ypos: 250 | width: 400 | height: 200
      |     + window | id: 2 | title: Arora (2)
      |              | xpos: 170 | ypos: 150 | width: 300 | height: 200
      + sleep | milliseconds: 1000
      + inline | description: move window 3
      | + window_layout
      |   + boundary | width: 1024 | height: 768
      |     + window | id: 1 | title: Genode Toolchain
      |              | xpos: 100 | ypos:  50 | width: 200 | height: 200
      |     + window | id: 3 | title: Launchpad | focused: yes
      |              | xpos: 310 | ypos: 300 | width: 500 | height: 300
      |     + window | id: 2 | title:  Arora (2)
      |              | xpos: 170 | ypos: 150 | width: 300 | height: 200
      + sleep | milliseconds: 1000
      + empty
      + sleep | milliseconds: 1000

+ start decorator | ram: 8M
  + route
    + service ROM | label: pointer       | + child report_rom
    + service ROM | label: window_layout | + child dynamic_rom
    + any-service
      + parent
      + any-child
  + config
    + default-policy
-
}

build { app/decorator }

build_boot_image [build_artifacts]

run_genode_until forever
