create_boot_directory

import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/pkg/[drivers_interactive_pkg] \
                  [depot_user]/src/report_rom \
                  [depot_user]/src/fs_rom \
                  [depot_user]/src/vfs \
                  [depot_user]/src/nitpicker \
                  [depot_user]/src/init \
                  [depot_user]/src/vfs_ttf \
                  [depot_user]/src/libc \
                  [depot_user]/src/shim \
                  [depot_user]/raw/ttf-bitstream-vera-minimal

create_tar_from_depot_binaries [run_dir]/genode/depot.tar \
                               [depot_user]/pkg/chroot \
                               [depot_user]/pkg/system_shell \
                               [depot_user]/pkg/fonts_fs \
                               [depot_user]/pkg/wm \
                               [depot_user]/pkg/nano3d \
                               [depot_user]/pkg/window_layouter \
                               [depot_user]/pkg/motif_decorator \
                               [depot_user]/pkg/themed_decorator \
                               [depot_user]/pkg/sticks_blue_backdrop

proc current_pkg { pkg } { return $pkg/[_current_depot_archive_version pkg $pkg] }

install_config {
config
+ parent-provides
  + service ROM
  + service IRQ
  + service IO_MEM
  + service IO_PORT
  + service PD
  + service RM
  + service CPU
  + service LOG

+ default-route
  + any-service
    + parent
    + any-child

+ default | caps: 100 | ram: 1M

+ start timer
  + provides | + service Timer

+ start drivers | caps: 1500 | ram: 64M | managing_system: yes
  + binary init
  + route
    + service ROM | label: config | + parent | label: drivers.config
    + service Timer               | + child timer
    + service Capture             | + child nitpicker
    + service Event               | + child nitpicker
    + any-service                 | + parent

+ start nitpicker | ram: 4M
  + provides
    + service Gui
    + service Capture
    + service Event
  + config | focus: rom
    + capture
    + event
    + background | color: #123456
    + domain pointer | layer: 1 | content: client | label: no | origin: pointer
    + domain default | layer: 3 | content: client | label: no | hover:  always
    + policy | label_prefix: pointer | domain: pointer
    + default-policy                 | domain: default

+ start pointer
  + route
    + service Gui | + child nitpicker
    + any-service
      + parent
      + any-child

+ start report_rom
  + binary report_rom
  + provides
    + service Report
    + service ROM
  + config | verbose: no
    + policy | label:  depot_deploy -> blueprint | report: depot_query -> blueprint
    + policy | label:  depot_query -> query      | report: depot_deploy -> query
    + policy | label:  dynamic -> config         | report: depot_deploy -> init.config
    + policy | label:  dynamic -> clipboard      | report: dynamic -> clipboard

+ start vfs | ram: 4M
  + provides | + service File_system
  + config
    + vfs | + tar depot.tar
    + policy | label_prefix: depot_query -> depot -> | root: /
    + policy | label_prefix: fs_rom ->               | root: /

+ start fs_rom | ram: 50M
  + provides | + service ROM
  + route
    + service File_system | + child vfs
    + any-service         | + parent

+ start depot_query | ram: 2M
  + config | query: rom
    + vfs | + dir depot | + fs | label: depot -> /
  + route
    + service ROM | label: query | + child report_rom
    + service File_system        | + child vfs
    + any-service
      + parent
      + any-child

+ start ram_fs | ram: 8M
  + binary vfs
  + provides | + service File_system
  + config
    + vfs | + ram
    + default-policy | root: / | writeable: yes

+ start depot_deploy
  + config | arch: } [depot_spec] {
  | + static
  |   + parent-provides
  |     + service ROM
  |     + service CPU
  |     + service PD
  |     + service LOG
  |     + service Timer
  |     + service Gui
  |     + service File_system
  |     + service Report
  | + common_routes
  |   + service ROM | label_last: ld.lib.so | + parent
  |   + service ROM | label_last: init      | + parent
  |   + service CPU                         | + parent
  |   + service PD                          | + parent
  |   + service LOG                         | + parent
  |   + service Timer                       | + parent
  |
  | + start recall_fs | pkg: } [depot_user]/pkg/[current_pkg chroot] {
  |   + route | + service File_system | + parent
  |   + config
  |     + default-policy | path_prefix: /recall | writeable: yes
  |
  | + start wm | pkg: } [depot_user]/pkg/[current_pkg wm] {
  |   + route | + service Gui | + parent
  |
  | + start window_layouter | pkg: } [depot_user]/pkg/[current_pkg window_layouter] {
  |   + route
  |     + service ROM | label: window_list              | + child wm
  |     + service ROM | label: focus_request            | + child wm
  |     + service ROM | label: hover                    | + child wm
  |     + service ROM | label: decorator_margins        | + child wm
  |     + service ROM | label: rules                    | + child wm
  |     + service Report                                | + child wm
  |     + service Gui                                   | + child wm
  |     + service File_system | label_prefix: recall -> | + child recall_fs
  |
  | + start themed_decorator | pkg: } [depot_user]/pkg/[current_pkg themed_decorator] {
  |   + route
  |     + service ROM | label: window_layout | + child wm
  |     + service ROM | label: pointer       | + child wm
  |     + service Report                     | + child wm
  |     + service Gui                        | + child wm
  |
  | + start nano3d | pkg: } [depot_user]/pkg/[current_pkg nano3d] {
  |   + route | + service Gui | + child wm
  |   + config | shape: cube
  |
  | + start fonts_fs | pkg: } [depot_user]/pkg/[current_pkg fonts_fs] {
  |   + route | + service ROM | label: config | + parent | label: fonts.config
  |
  | + start system_shell | pkg: } [depot_user]/pkg/[current_pkg system_shell] {
  |   + route
  |     + service Gui                                  | + child wm
  |     + service File_system | label_prefix: fonts -> | + child fonts_fs
  |     + service File_system                          | + parent
  |     + service Report | label: clipboard            | + parent | label: clipboard
  |     + service ROM | label: clipboard               | + parent | label: clipboard
  |     + service ROM | label: vimrc                   | + parent | label: vimrc
  |     + service ROM | label_last: cached_fs_rom      | + parent | label: fs_rom
  + route
    + service ROM    | label: blueprint | + child report_rom
    + service Report | label: query     | + child report_rom
    + service Report | label: clipboard | + child report_rom
    + service ROM    | label: clipboard | + child report_rom
    + any-service
      + parent
      + any-child

+ start dynamic | caps: 8000 | ram: 180M
  + binary init
  + route
    + service ROM | label_last: ld.lib.so    | + parent
    + service ROM | label_last: init         | + parent
    + service ROM | label_last: shim         | + parent
    + service ROM | label: config            | + child report_rom
    + service ROM | label_last: fonts.config | + parent
    + service ROM | label_last: vimrc        | + parent
    + service ROM | label_last: fs_rom       | + parent
    + service ROM                            | + child fs_rom
    + service Timer                          | + child timer
    + service Gui | label_last: backdrop     | + child nitpicker | label: backdrop
    + service File_system                    | + child ram_fs
    + any-service
      + parent
      + any-child
-
}

build { app/depot_query app/depot_deploy }

copy_file [genode_dir]/repos/gems/sculpt/fonts/default [run_dir]/genode/fonts.config
copy_file [genode_dir]/repos/ports/recipes/raw/system_shell/system_shell.config [run_dir]/genode/

#
# Pin the nitpicker focus to the window manager by providing a static focus ROM
#
set fd [open [run_dir]/genode/focus w]
puts $fd "focus | label: dynamic -> wm -> focus\n-"
close $fd

# write default vimrc file
set vimrc_fd [open [run_dir]/genode/vimrc w]
puts $vimrc_fd {
set noloadplugins
set hls
set nocompatible
set laststatus=2
set noswapfile
set viminfo=}
close $vimrc_fd

build_boot_image [build_artifacts]

run_genode_until forever

