build { init app/depot_query app/depot_deploy }

create_boot_directory

import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/src/report_rom \
                  [depot_user]/src/fs_rom \
                  [depot_user]/src/vfs \
                  [depot_user]/src/init

create_tar_from_depot_binaries [run_dir]/genode/depot.tar \
                               [depot_user]/pkg/test-fs_report

proc query_pkg {} {
	return test-fs_report/[_current_depot_archive_version pkg test-fs_report] }

install_config {
config
+ parent-provides
  + service ROM
  + service IRQ
  + service IO_MEM
  + service IO_PORT
  + service PD
  + service RM
  + service CPU
  + service LOG

+ default-route
  + any-service
    + parent
    + any-child

+ default | caps: 200 | ram: 2M

+ start timer
  + provides | + service Timer

+ start report_rom
  + binary report_rom
  + provides
    + service Report
    + service ROM
  + config | verbose: yes
    + policy | label:  depot_deploy -> blueprint | report: depot_query -> blueprint
    + policy | label:  depot_query -> query      | report: depot_deploy -> query
    + policy | label:  dynamic -> config         | report: depot_deploy -> init.config

+ start vfs | ram: 4M
  + provides | + service File_system
  + config
    + vfs
    | + tar depot.tar
    | + dir badguy
    |   + dir pkg
    |     + dir invalid
    |       + dir current
    |         + inline archives
    |         + inline runtime
    |           + runtime | ram: 1M | caps: 100 | binary: chroot
    |             + content
    |               + rom | label: chroot
    + policy | label_prefix: depot_query -> depot -> | root: /
    + policy | label_prefix: fs_rom ->               | root: /

+ start fs_rom | ram: 5M
  + provides
    + service ROM
+ start depot_query | ram: 2M
  + config | query: rom
    + vfs | + dir depot | + fs | label: depot -> /
  + route
    + service ROM | label: query | + child report_rom
    + any-service
      + parent
      + any-child

+ start depot_deploy
  + config | arch: } [depot_spec] {
  | + static
  |   + parent-provides
  |     + service ROM
  |     + service CPU
  |     + service PD
  |     + service LOG
  |     + service Timer
  | + common_routes
  |   + service ROM | label_last: ld.lib.so | + parent
  |   + service ROM | label_last: init      | + parent
  |   + service CPU                         | + parent
  |   + service PD                          | + parent
  |   + service LOG                         | + parent
  |   + service Timer                       | + parent
  | + start invalid | pkg: badguy/pkg/invalid/current
  | + start test | pkg: } [depot_user] {/pkg/} [query_pkg] {
  + route
    + service ROM | label: blueprint | + child report_rom
    + any-service
      + parent
      + any-child

+ start dynamic | caps: 8000 | ram: 64M
  + binary init
  + route
    + service ROM | label_last: ld.lib.so | + parent
    + service ROM | label_last: init      | + parent
    + service ROM | label: config         | + child report_rom
    + service ROM                         | + child fs_rom
    + service Timer                       | + child timer
    + any-service
      + parent
      + any-child
-
}

build_boot_image [build_artifacts]

append qemu_args " -nographic "

run_genode_until {.*\] child "test-fs_report" exited with exit value 0.*\n} 30

