assert {![have_spec riscv]}

proc jent_avail { } {
	if {[have_board pbxa9]} { return 0 }
	if {[have_board zynq_qemu]} { return 0 }
	return 1
}

proc jent_avail_attr { } {
	if {[jent_avail]} { return "yes" }
	return "no"
}

proc passphrase { } { return abcdefgh }

proc lx_fs_dir { } { return bin/file_vault_client_dir }

proc lx_fs_dir_template { } { return $::env(LX_FS_DIR_TEMPLATE) }

proc lx_fs_dir_template_set { } { return [info exists ::env(LX_FS_DIR_TEMPLATE)] }

proc container_initialized { } { return [expr [have_board linux] && [lx_fs_dir_template_set]] }

proc bash_profile { } {
	if {[container_initialized]} { return file_vault_client_2.sh }
	return file_vault_client_1.sh
}

if {[have_board linux]} {
	if {[lx_fs_dir_template_set]} {
		if {[file normalize [lx_fs_dir_template]] == [file normalize [lx_fs_dir]]} {
			puts ""
			puts "Error: please set LX_FS_DIR_TEMPLATE to something other than [lx_fs_dir]"
			puts ""
			exit -1
		}
		puts ""
		puts "Use lx_fs directory template [lx_fs_dir_template]"
		puts ""
	}
}

build {
	lib/tresor lib/vfs_tresor_trust_anchor lib/vfs_tresor_crypto_aes_cbc
	lib/vfs_tresor app/tresor_init_trust_anchor app/tresor_init app/file_vault }

create_boot_directory

lappend archives \
	[depot_user]/src/[base_src] \
	[depot_user]/src/init \
	[depot_user]/src/libc \
	[depot_user]/src/zlib \
	[depot_user]/src/fs_query \
	[depot_user]/src/vfs_block \
	[depot_user]/src/vfs \
	[depot_user]/src/openssl \
	[depot_user]/src/fs_tool \
	[depot_user]/src/fs_utils \
	[depot_user]/src/posix \
	[depot_user]/src/vfs_pipe \
	[depot_user]/src/vfs_rump \
	[depot_user]/src/fs_rom \
	[depot_user]/src/log_terminal \
	[depot_user]/src/sandbox \
	[depot_user]/src/coreutils \
	[depot_user]/src/bash \
	[depot_user]/src/report_rom \
	[depot_user]/src/dynamic_rom

lappend_if [jent_avail]       archives [depot_user]/src/vfs_jitterentropy
lappend_if [have_board linux] archives [depot_user]/src/lx_fs

import_from_depot {*}$archives


proc data_fs_start_nodes_lx_fs { } { return {

+ start data_fs | caps: 200 | ram: 4M | ld: no
  + binary lx_fs
  + provides | + service File_system
  + config
    + policy | label_prefix: file_vault -> data | root: /file_vault_client_dir/data
                                                | writeable: yes
+ start trust_anchor_fs | caps: 200 | ram: 4M | ld: no
  + binary lx_fs
  + provides | + service File_system
  + config
    + policy | label_prefix: file_vault -> trust_anchor | root: /file_vault_client_dir/trust_anchor
                                                        | writeable: yes
} }

proc data_fs_start_nodes_vfs { } { return {

+ start data_fs | caps: 100 | ram: 10M
  + binary vfs
  + provides | + service File_system
  + config
    + vfs | + dir data | + ram
    + policy | label_prefix: file_vault -> data | root: /data | writeable: yes

+ start trust_anchor_fs | caps: 100 | ram: 4M
  + binary vfs
  + provides | + service File_system
  + config
    + vfs | + dir trust_anchor | + ram
    + policy | label_prefix: file_vault -> trust_anchor | root: /trust_anchor
                                                        | writeable:    yes
} }

proc data_fs_start_nodes { } {
	if {[have_board linux]} {
		return [data_fs_start_nodes_lx_fs]
	} else {
		return [data_fs_start_nodes_vfs]
	}
}

proc passphrase_ui_config_node { } {
	if {[container_initialized]} {
		return "ui_config | passphrase: [passphrase]"
	} else {
		return "ui_config | passphrase: [passphrase] | client_fs_size: 1M | journaling_buf_size: 1M"
	}
}

append config {

config
+ parent-provides
  + service ROM
  + service LOG
  + service RM
  + service CPU
  + service PD
  + service IRQ
  + service IO_MEM
  + service IO_PORT

+ default-route
  + any-service
    + parent
    + any-child

+ start timer | caps: 200 | ram: 1M
  + provides | + service Timer

+ start dynamic_rom | caps: 100 | ram: 4M
  + provides | + service ROM
  + config | verbose: yes
    + rom file_vault_ui_config
      + inline | + ui_config
      + sleep  | milliseconds: 3000
      + inline | + } [passphrase_ui_config_node] {
      + sleep  | milliseconds: 50000
      + inline | + ui_config
      + sleep  | milliseconds: 3600000
    + rom dynamic_init_config
      + inline | + config
      + sleep  | milliseconds: 9000
      + inline
      | + config
      |   + parent-provides
      |   | + service ROM
      |   | + service PD
      |   | + service CPU
      |   | + service LOG
      |   | + service Timer
      |   | + service File_system
      |   + start log_terminal | caps: 110 | ram: 2M
      |   | + provides | + service Terminal
      |   | + route | + any-service | + parent
      |   + start vfs | caps: 120 | ram: 30M
      |   | + provides | + service File_system
      |   | + config
      |   | | + vfs
      |   | |   + tar coreutils.tar
      |   | |   + tar bash.tar
      |   | |   + dir home | + ram
      |   | |   + dir share
      |   | |   + dir tmp  | + ram
      |   | |   + dir dev
      |   | |     + zero
      |   | |     + null
      |   | |     + terminal
      |   | |     + dir pipe | + pipe
      |   | |     + inline rtc | : 2018-01-01 00:01
      |   | | + policy | label_prefix: fs_rom | root: /
      |   | | + default-policy                | root: / | writeable: yes
      |   | + route
      |   |   + service Terminal | + child log_terminal
      |   |   + any-service      | + parent
      |   + start fs_rom | caps: 100 | ram: 8M
      |   | + provides | + service ROM
      |   | + config
      |   | + route
      |   |   + service File_system | + child vfs
      |   |   + any-service         | + parent
      |   + start bash | caps: 500 | ram: 32M
      |     + binary /bin/bash
      |     + config
      |     | + libc | stdin:  /dev/terminal | stdout: /dev/terminal
      |     |        | stderr: /dev/terminal | rtc:    /dev/rtc
      |     |        | pipe:   /dev/pipe
      |     | + vfs
      |     |   + fs | label: shell | buffer_size: 1M
      |     |   + dir file_vault | + fs | label: file_vault | buffer_size: 1M
      |     |   + rom .profile | label: } [bash_profile] {
      |     | + arg bash | : --login
      |     | + env TERM | : screen
      |     | + env HOME | : /
      |     | + env PATH | : /bin
      |     + route
      |       + service File_system | label: shell      | + child vfs | label: /
      |       + service File_system | label: file_vault | + parent | label: bash -> file_vault -> /
      |       + service ROM | label_suffix: .lib.so     | + parent
      |       + service ROM | label_last: /bin/bash     | + child fs_rom
      |       + service ROM | label_prefix: /bin        | + child fs_rom
      |       + any-service                             | + parent
      + sleep | milliseconds: 3600000

+ start report_rom | caps: 70 | ram: 1M
  + provides
    + service ROM
    + service Report
  + config | verbose: yes

} [data_fs_start_nodes] {

+ start file_vault | caps: 1000 | ram: 80M
  + provides | + service File_system
  + config | jitterentropy_available: } [jent_avail_attr] {
    + vfs | + dir tresor | + fs | label: tresor -> /
  + route
    + service ROM | label: ui_config
      + child dynamic_rom | label: file_vault_ui_config
    + service Report | label: ui_report
      + child report_rom
    + service File_system | label_prefix: tresor_trust_anchor_vfs -> storage_dir
      + child trust_anchor_fs | identity: file_vault -> trust_anchor
    + service File_system | label_prefix: tresor_init ->
      + child data_fs | identity: file_vault -> data
    + service File_system | label_prefix: tresor ->
      + child data_fs | identity: file_vault -> data
    + service File_system | label_prefix: fs_query ->
      + child data_fs | identity: file_vault -> data
    + service File_system | label_prefix: image_fs_query ->
      + child data_fs | identity: file_vault -> data
    + service File_system | label_prefix: tresor_vfs -> tresor_fs
      + child data_fs | identity: file_vault -> data
    + service File_system | label_prefix: truncate_file -> tresor
      + child data_fs | identity: file_vault -> data
    + service Timer | + child timer
    + any-service   | + parent

+ start dynamic_init | caps: 1000 | ram: 100M
  + binary init
  + route
    + service ROM | label: config
      + child dynamic_rom | label: dynamic_init_config
    + service File_system | label_prefix: bash -> file_vault ->
      + child file_vault
    + service Timer | + child timer
    + any-service   | + parent
-
}

exec cp [repository_contains run/[bash_profile]]/run/[bash_profile] bin/

install_config $config

if {[have_board linux]} {
	exec rm -rf [lx_fs_dir]
	if {[lx_fs_dir_template_set]} {
		exec cp -r [lx_fs_dir_template] [lx_fs_dir]
	} else {
		exec mkdir -p [lx_fs_dir]/data
		exec mkdir -p [lx_fs_dir]/trust_anchor
	}
}

append boot_modules [build_artifacts]
lappend boot_modules [bash_profile]

lappend_if [have_board linux] boot_modules [file tail [lx_fs_dir]]

build_boot_image $boot_modules

append qemu_args " -display none "
run_genode_until "child \"bash\" exited with exit value 0.*\n" 100

grep_output {\[init -> dynamic_init -> log_terminal\].*}

if {[container_initialized]} {
	compare_output_to {
[init -> dynamic_init -> log_terminal] total 1
[init -> dynamic_init -> log_terminal] drwx------ 1 root 0  0 1970-01-01 dir_1
[init -> dynamic_init -> log_terminal] -rwx------ 1 root 0 18 2018-01-01 file_1
[init -> dynamic_init -> log_terminal] drwx------ 1 root 0  0 2018-01-01 lost+found
[init -> dynamic_init -> log_terminal] total 1
[init -> dynamic_init -> log_terminal] -rwx------ 1 root 0 66 2018-01-01 file_2
[init -> dynamic_init -> log_terminal] Ein zweiter Test.
[init -> dynamic_init -> log_terminal] Eine weitere Datei.
[init -> dynamic_init -> log_terminal] Mit mehr Inhalt.
[init -> dynamic_init -> log_terminal] Und Sonderzeichen: /.:($)=%!
	}
} else {
	compare_output_to {
[init -> dynamic_init -> log_terminal] Hallo Welt!
[init -> dynamic_init -> log_terminal] Ein zweiter Test.
[init -> dynamic_init -> log_terminal] total 1
[init -> dynamic_init -> log_terminal] -rwx------ 1 root 0 18 2018-01-01 file_1
[init -> dynamic_init -> log_terminal] drwx------ 1 root 0  0 2018-01-01 lost+found
[init -> dynamic_init -> log_terminal] Eine weitere Datei.
[init -> dynamic_init -> log_terminal] Mit mehr Inhalt.
[init -> dynamic_init -> log_terminal] Eine weitere Datei.
[init -> dynamic_init -> log_terminal] Mit mehr Inhalt.
[init -> dynamic_init -> log_terminal] Und Sonderzeichen: /.:($)=%!
[init -> dynamic_init -> log_terminal] total 1
[init -> dynamic_init -> log_terminal] drwx------ 1 root 0  0 1970-01-01 dir_1
[init -> dynamic_init -> log_terminal] -rwx------ 1 root 0 18 2018-01-01 file_1
[init -> dynamic_init -> log_terminal] drwx------ 1 root 0  0 2018-01-01 lost+found
[init -> dynamic_init -> log_terminal] total 1
[init -> dynamic_init -> log_terminal] -rwx------ 1 root 0 66 2018-01-01 file_2
	}
}

if {[have_cmd_switch --autopilot] && [have_board linux]} { exec rm -rf [lx_fs_dir] }
