proc jent_avail { } {
	if {[have_board pbxa9]} { return 0 }
	if {[have_board zynq_qemu]} { return 0 }
	return 1
}

proc jent_avail_attr { } {
	if {[jent_avail]} { return "yes" }
	return "no"
}

build { app/file_vault app/file_vault_gui lib/dialog }

create_boot_directory

lappend archives \
	[depot_user]/src/[base_src] \
	[depot_user]/src/init \
	[depot_user]/src/libc \
	[depot_user]/src/zlib \
	[depot_user]/src/fs_query \
	[depot_user]/src/tresor \
	[depot_user]/src/vfs_block \
	[depot_user]/src/report_rom \
	[depot_user]/src/vfs \
	[depot_user]/src/openssl \
	[depot_user]/src/fs_tool \
	[depot_user]/src/fs_utils \
	[depot_user]/src/posix \
	[depot_user]/src/vfs_rump \
	[depot_user]/src/sandbox \
	[depot_user]/src/nitpicker \
	[depot_user]/src/menu_view \
	[depot_user]/src/libpng \
	[depot_user]/pkg/fonts_fs \
	[depot_user]/pkg/[drivers_interactive_pkg]

lappend_if [jent_avail]       archives [depot_user]/src/vfs_jitterentropy
lappend_if [have_board linux] archives [depot_user]/src/lx_fs

import_from_depot {*}$archives

proc data_fs_start_nodes_lx_fs { } { return {

+ start data_fs | caps: 200 | ram: 4M | ld: no
  + binary lx_fs
  + provides | + service File_system
  + config
    + policy | label_prefix: file_vault -> data | root: /file_vault_gui_dir/data
                                                | writeable: yes

+ start trust_anchor_fs | caps: 200 | ram: 4M | ld: no
  + binary lx_fs
  + provides | + service File_system
  + config
    + policy | label_prefix: file_vault -> trust_anchor | root: /file_vault_gui_dir/trust_anchor
                                                        | writeable: yes
} }

proc data_fs_start_nodes_vfs { } { return {
config
+ start data_fs | caps: 2000 | ram: 200M
  + binary vfs
  + provides | + service File_system
  + config
    + vfs | + dir data | + ram
    + policy | label_prefix: file_vault -> data | root: /data | writeable: yes

+ start trust_anchor_fs | caps: 100 | ram: 5M
  + binary vfs
  + provides | + service File_system
  + config
    + vfs | + dir trust_anchor | + ram
    + policy | label_prefix: file_vault -> trust_anchor | root: /trust_anchor
                                                        | writeable: yes
} }

proc data_fs_start_nodes { } {
	if {[have_board linux]} {
		return [data_fs_start_nodes_lx_fs]
	} else {
		return [data_fs_start_nodes_vfs]
	}
}

install_config {

config
+ parent-provides
  + service ROM
  + service LOG
  + service RM
  + service CPU
  + service PD
  + service IRQ
  + service IO_MEM
  + service IO_PORT

+ default-route
  + any-service
    + parent
    + any-child

+ start timer | caps: 200 | ram: 1M
  + provides | + service Timer

+ start drivers | caps: 1500 | ram: 64M | managing_system: yes
  + binary init
  + route
    + service Timer               | + child timer
    + service Capture             | + child nitpicker
    + service Event               | + child nitpicker
    + service ROM | label: config | + parent | label: drivers.config
    + any-service                 | + parent

+ start nitpicker | caps: 100 | ram: 4M
  + provides
    + service Gui
    + service Capture
    + service Event
  + config | focus: rom
    + capture
    + event
    + background | color: #123456
    + domain pointer | layer: 1 | content: client | label: no | origin: pointer
    + domain default | layer: 3 | content: client | label: no | hover: always
    + domain second  | layer: 2 | content: client | label: no | hover: always
                                                  | xpos: 200 | ypos: 300
    + policy | label_prefix: pointer        | domain: pointer
    + policy | label_prefix: file_vault_gui | domain: second
    + default-policy                        | domain: default

+ start pointer | caps: 100 | ram: 1M

+ start fonts_fs | caps: 150 | ram: 4M
  + binary vfs
  + provides | + service File_system
  + config
  | + vfs
  |   + rom Vera.ttf
  |   + rom VeraMono.ttf
  |   + dir fonts
  |     + dir title      | + ttf regular | path: /Vera.ttf     | size_px: 18 | cache: 256K
  |     + dir text       | + ttf regular | path: /Vera.ttf     | size_px: 14 | cache: 256K
  |     + dir annotation | + ttf regular | path: /Vera.ttf     | size_px: 11 | cache: 256K
  |     + dir monospace  | + ttf regular | path: /VeraMono.ttf | size_px: 14 | cache: 256K
  | + policy | label_prefix: file_vault_gui -> fonts | root: /fonts
  + route
    + service ROM | label: config | + parent | label: fonts_fs.config
    + any-service                 | + parent

} [data_fs_start_nodes] {

+ start report_rom | caps: 100 | ram: 1M
  + provides
    + service Report
    + service ROM
  + config | verbose: yes
    + policy | label: file_vault_gui -> ui_report | report: file_vault -> ui_report
    + policy | label: file_vault -> ui_config     | report: file_vault_gui -> ui_config

+ start file_vault | caps: 1200 | ram: 100M
  + config | jitterentropy_available: } [jent_avail_attr] {
    + vfs | + dir tresor | + fs | label: tresor -> /
  + route
    + service File_system | label_prefix: tresor_trust_anchor_vfs -> storage_dir
      + child trust_anchor_fs | identity: file_vault -> trust_anchor
    + service File_system | label_prefix: tresor_init ->
      + child data_fs | identity: file_vault -> data
    + service File_system | label_prefix: tresor ->
      + child data_fs | identity: file_vault -> data
    + service File_system | label_prefix: image_fs_query ->
      + child data_fs | identity: file_vault -> data
    + service File_system | label_prefix: tresor_vfs -> tresor_fs
      + child data_fs | identity: file_vault -> data
    + service File_system | label_prefix: truncate_file -> tresor
      + child data_fs | identity: file_vault -> data
    + service ROM    | label: ui_config | + child report_rom
    + service Report | label: ui_report | + child report_rom
    + service Timer                     | + child timer
    + service PD                        | + parent
    + service ROM                       | + parent
    + service CPU                       | + parent
    + service LOG                       | + parent
    + service RM                        | + parent

+ start file_vault_gui | caps: 400 | ram: 8M
  + route
    + service File_system               | + child fonts_fs
    + service Gui                       | + child nitpicker
    + service ROM | label: ui_report    | + child report_rom
    + service Report | label: ui_config | + child report_rom
    + service Timer                     | + child timer
    + service PD                        | + parent
    + service ROM                       | + parent
    + service CPU                       | + parent
    + service LOG                       | + parent
    + service RM                        | + parent
-
}


if {[have_board linux]} {
	exec mkdir -p bin/file_vault_gui_dir/data
	exec mkdir -p bin/file_vault_gui_dir/trust_anchor
}
append boot_modules [build_artifacts]

lappend_if [have_board linux] boot_modules file_vault_gui_dir

set fd [open [run_dir]/genode/focus w]
puts $fd "focus | label: file_vault_gui ->\n-"
close $fd

append qemu_args " -display gtk "
build_boot_image $boot_modules
run_genode_until forever
