create_boot_directory

import_from_depot genodelabs/src/[base_src] \
                  genodelabs/pkg/[drivers_interactive_pkg] \
                  genodelabs/src/init \
                  genodelabs/src/dynamic_rom \
                  genodelabs/src/nitpicker \
                  genodelabs/src/demo \
                  genodelabs/src/libc \
                  genodelabs/src/libpng \
                  genodelabs/src/zlib

install_config {
<config>
	<parent-provides>
		<service name="PD"/>
		<service name="CPU"/>
		<service name="ROM"/>
		<service name="RM"/>
		<service name="LOG"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
	</parent-provides>

	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Timer"/></provides>
	</start>

	<start name="drivers">
		<resource name="RAM" quantum="32M"/>
		<binary name="init"/>
		<route>
			<service name="ROM" label="config"> <parent label="drivers.config"/> </service>
			<service name="Timer"> <child name="timer"/> </service>
			<any-service> <parent/> </any-service>
		</route>
		<provides>
			<service name="Input"/> <service name="Framebuffer"/>
		</provides>
	</start>

	<start name="nitpicker">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Nitpicker"/></provides>
		<config>
			<domain name="pointer" layer="1" content="client" label="no" origin="pointer" />
			<domain name="default" layer="3" content="client" label="no" hover="always" />

			<policy label_prefix="pointer" domain="pointer"/>
			<default-policy domain="default"/>
		</config>
	</start>

	<start name="pointer">
		<resource name="RAM" quantum="1M"/>
		<route>
			<service name="Nitpicker"> <child name="nitpicker" /> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

	<start name="dynamic_rom">
		<resource name="RAM" quantum="4M"/>
		<provides><service name="ROM"/></provides>
		<config verbose="yes">
			<rom name="dialog">
				<inline description="example menu">
					<dialog>
						<frame>
							<vbox>
								<button name="virtualbox">
									<label text="VirtualBox"/>
								</button>
								<button name="toolchain" hovered="yes">
									<label text="Tool chain"/>
								</button>
								<button name="log" hovered="yes" selected="yes">
									<label text="Log window"/>
								</button>
								<button name="config" selected="yes">
									<label text="Configuration"/>
								</button>
							</vbox>
						</frame>
					</dialog>
				</inline>
				<sleep milliseconds="2000" />
				<inline description="example menu">
					<dialog>
						<frame>
							<vbox>
								<button name="virtualbox" hovered="yes">
									<label text="VirtualBox"/>
								</button>
								<button name="toolchain">
									<label text="Tool chain"/>
								</button>
								<button name="log" selected="yes">
									<label text="Log window"/>
								</button>
								<button name="config" selected="yes" hovered="yes">
									<label text="Configuration"/>
								</button>
							</vbox>
						</frame>
					</dialog>
				</inline>
				<sleep milliseconds="2000" />
			</rom>
		</config>
	</start>

	<start name="menu_view">
		<resource name="RAM" quantum="5M"/>
		<config xpos="200" ypos="100">
			<libc stderr="/dev/log"/>
			<vfs>
				<tar name="menu_view_styles.tar" />
				<dir name="dev"> <log/> </dir>
			</vfs>
		</config>
		<route>
			<service name="ROM" label="dialog"> <child name="dynamic_rom" /> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

	<start name="scout">
		<resource name="RAM" quantum="64M" />
	</start>
</config>}

build { app/menu_view }

build_boot_image { menu_view menu_view_styles.tar }

run_genode_until forever
