source ${genode_dir}/repos/libports/run/qt6_common.inc

import_from_depot [depot_user]/src/dynamic_rom \
                  [depot_user]/src/mixer_gui_qt6

#
# Generate config
#

install_config {
config
+ parent-provides
  } [qt6_parent_provides] {
+ default | caps: 100
+ default-route
  + any-service
    + parent
    + any-child
} [qt6_start_nodes] {
+ start dynamic_rom | ram: 4M
  + provides | + service ROM
  + config | verbose: yes
    + rom channel_list
      + sleep | milliseconds: 1000
      + inline | description: first config update
        + channel_list
          + channel | type: input  | label: test-audio_out0               | name: right | number: 1 | active: 1 | volume: 0   | muted: 0
          + channel | type: input  | label: test-audio_out_click          | name: left  | number: 0 | active: 1 | volume: 75  | muted: 0
          + channel | type: input  | label: fancy_init -> test-audio_out1 | name: left  | number: 0 | active: 1 | volume: 75  | muted: 0
          + channel | type: input  | label: test-audio_out0               | name: left  | number: 0 | active: 1 | volume: 0   | muted: 0
          + channel | type: input  | label: test-audio_out_click          | name: right | number: 1 | active: 1 | volume: 75  | muted: 0
          + channel | type: input  | label: fancy_init -> test-audio_out1 | name: right | number: 1 | active: 1 | volume: 75  | muted: 0
          + channel | type: output | label: master                        | name: left  | number: 0 | active: 1 | volume: 100 | muted: 0
          + channel | type: output | label: master                        | name: right | number: 1 | active: 1 | volume: 100 | muted: 0
      + sleep | milliseconds: 1000
      + inline | description: second config update
        + channel_list
          + channel | type: input  | label: test-audio_out0               | name: right | number: 1 | active: 1 | volume: 100 | muted: 0
          + channel | type: input  | label: test-audio_out_click          | name: left  | number: 0 | active: 1 | volume: 75  | muted: 1
          + channel | type: input  | label: fancy_init -> test-audio_out1 | name: left  | number: 0 | active: 1 | volume: 25  | muted: 0
          + channel | type: input  | label: test-audio_out0               | name: left  | number: 0 | active: 1 | volume: 100 | muted: 0
          + channel | type: input  | label: test-audio_out_click          | name: right | number: 1 | active: 1 | volume: 15  | muted: 1
          + channel | type: input  | label: fancy_init -> test-audio_out1 | name: right | number: 1 | active: 1 | volume: 25  | muted: 0
          + channel | type: output | label: master                        | name: left  | number: 0 | active: 1 | volume: 100 | muted: 0
          + channel | type: output | label: master                        | name: right | number: 1 | active: 1 | volume: 100 | muted: 0

+ start mixer_gui_qt | caps: 250 | ram: 32M
  + config
    + vfs
      + dir dev
        + log
        + inline rtc | : 2018-01-01 00:01
      + dir pipe | + pipe
      + tar qt6_dejavusans.tar
      + tar qt6_libqgenode.tar
    + libc | stdout: /dev/log | stderr: /dev/log | pipe: /pipe | rtc: /dev/rtc
  + route
    + service Gui                             | + child wm
    + service Report | label: shape           | + child wm
    + service ROM    | label: channel_list    | + child dynamic_rom
    + service ROM    | label: mesa_gpu.lib.so | + parent            | label: mesa_gpu-softpipe.lib.so
    + any-service
      + parent
      + any-child
-
}

build_boot_image [qt6_boot_modules]

run_genode_until forever

# vi: set ft=tcl :
