build {
	core init
	app/sequence
	drivers/timer
	lib/libc_noux
	noux/minimal
	noux-pkg/coreutils
	server/vfs
	lib/vfs/audit
}

create_boot_directory

install_config {
	<config verbose="yes">
		<parent-provides>
			<service name="ROM"/>
			<service name="LOG"/>
			<service name="RM"/>
			<service name="CPU"/>
			<service name="PD"/>
			<service name="IRQ"/>
			<service name="IO_MEM"/>
			<service name="IO_PORT"/>
		</parent-provides>
		<default-route>
			<any-service> <any-child/> <parent/> </any-service>
		</default-route>
		<default caps="256"/>
		<start name="timer">
			<resource name="RAM" quantum="1M"/>
			<provides><service name="Timer"/></provides>
		</start>
		<start name="vfs">
			<resource name="RAM" quantum="2M"/>
			<provides><service name="File_system"/></provides>
			<config>
				<vfs>
					<dir name="coreutils">
						<tar name="coreutils.tar" /> </dir>
					<dir name="audit">
						<audit path="coreutils"/> </dir>
				</vfs>
				<default-policy root="audit"/>
			</config>
		</start>
		<start name="noux">
			<resource name="RAM" quantum="16M"/>
			<config verbose="yes" stdin="/null" stdout="/log" stderr="/log">
				<fstab> <null/> <log/> <fs/> </fstab>
				<start name="/bin/uname"> <arg value="-a"/> </start>
			</config>
		</start>
	</config>
}

build_boot_image {
	core init ld.lib.so
	coreutils.tar
	libc_noux.lib.so
	libm.lib.so
	noux libc.lib.so vfs.lib.so
	posix.lib.so
	sequence
	timer
	vfs_audit.lib.so
	vfs
}

append qemu_args " -nographic -serial mon:stdio "

# coreutils.tar is really huge when built for x86_64

run_genode_until {child "sequence" exited with exit value 0.*\n} 30
