#
# \brief  Sculpt OS
# \author Norman Feske
# \date   2017-09-07
#

#
# Note: the string must be exactly 5 bytes long.
#
proc sculpt_version { } { return "26.03" }


proc install_hid { path args } {
	set content ""
	append content {*}$args
	set fd [open $path w]
	puts $fd [string trim $content]
	close $fd
}


proc validate_hid { schema file } {

	lappend cmd [genode_dir]/tool/hid check
	lappend cmd --hsd-dir [run_dir]/genode --schema $schema $file

	if {[catch {exec {*}$cmd } result]} {
		puts stderr "Error: invalid $file (schema '$schema')"
		puts stderr $result
		if {[error_at_any_line $result]} { exit 1 }
	}
}


proc log_core { } {

	global ::env

	if {[info exists ::env(LOG)]} {
		if {$::env(LOG) == "core"} { return true }
	}

	return false
}


if {[log_core]} {
	if {[have_spec nova]} {
		proc kernel_output { } { return "serial logmem" }
	}
} else {
	# disable default enabled serial log output via core
	proc boot_output { } { return "" }

	if {[have_spec nova]} {
		proc kernel_output { } { return "logmem" }
	}
}


##
## Utilities for querying the ingredients of Sculpt
##

##
# Return path to the sculpt definition file that contains the list of
# ingredients
#
proc sculpt_path { } {

	global ::env

	set filename "default-[board].sculpt"
	if {[info exists ::env(SCULPT)]} {
		set filename "$::env(SCULPT)-[board].sculpt" }

	return [select_from_repositories [file join sculpt $filename]]
}


##
# Return list of ingredients of scenario supplied via the 'SCULPT' argument
#
# If 'SCULPT' is not specified, use 'sculpt/default.sculpt'.
#
proc sculpt_ingredients { } {

	global _sculpt_ingredients

	if {![info exists _sculpt_ingredients]} {
		set fh [open [sculpt_path] "RDONLY"]
		set _sculpt_ingredients [split [read $fh] "\n"]
		close $fh
	}

	return $_sculpt_ingredients
}


proc ingredients_of_type { type } {

	set result {}
	set line 1
	foreach i [sculpt_ingredients] {

		# skip comment lines
		if {[string match "#*" $i]} {
			continue }

		# skip empty lines
		if {[string match "" $i]} {
			continue }

		regexp {^(.*?):\s*(.*)\s*$} $i dummy tag values

		if {$tag == $type} {
			lappend result {*}$values}

		incr line
	}
	return $result
}


proc single_ingredient { type default } {

	set ingredient [ingredients_of_type $type]

	if {[llength $ingredient] == 0} {
		return $default }

	if {[llength $ingredient] > 1} {
		puts stderr "Error: ambigious selection of '$type' in [sculpt_path]"
		exit
	}
	return $ingredient
}


proc ingredient_path { type ingredient } {

	set rep_rel_path [file join sculpt $type $ingredient]

	lappend paths {*}[gather_from_repositories "$rep_rel_path-[board]"] \
	              {*}[gather_from_repositories "$rep_rel_path"]

	if {[llength $paths] == 0} {
		puts stderr "Error: $rep_rel_path not present in any repository"
		exit -9
	}
	if {[llength $paths] > 1} {
		puts "multiple candidates for '$rep_rel_path'"
		set prefix "using ->"
		foreach path $paths {
			puts "$prefix $path"
			regsub -all {.} $prefix " " prefix
		}
	}
	return [lindex $paths 0]
}


##
# Return directory for assembling the initial model
#
# The directory structure for the initial model is created at the run
# directory, which is imported as 'model.tar' into the model fs.
#
proc model { } { return [file join [run_dir] model] }


##
## System-image content imported from depot archives
##

create_boot_directory


proc prefixed_with_depot_user { paths } {
	return [lmap path $paths { file join [depot_user] $path }] }


import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/pkg/sculpt \
                  {*}[prefixed_with_depot_user [ingredients_of_type import]]


##
## Static init configuration
##

# each line in the following definitions must be indented with 4 spaces

set driver_routes(pc) {
    + service ROM | label: usb               | + parent | label: pc_usb_host
}

set driver_routes(mnt_reform2) {
    + service ROM | label: fb                | + parent | label: imx8mq_fb
    + service ROM | label: fb.dtb            | + parent | label: imx8mq_fb-mnt_reform2.dtb
    + service ROM | label: mmc               | + parent | label: imx8mq_sd_card
    + service ROM | label: mmc.dtb           | + parent | label: imx8mq_sd_card-mnt_reform2.dtb
    + service ROM | label: usb               | + parent | label: imx8m_usb_host
    + service ROM | label: usb.dtb           | + parent | label: imx8m_usb_host-mnt_reform2.dtb
}

set driver_routes(mnt_pocket) {
    + service ROM | label: fb                | + parent | label: imx8mq_fb
    + service ROM | label: fb.dtb            | + parent | label: imx8mq_fb-mnt_pocket.dtb
    + service ROM | label: mmc               | + parent | label: imx8mq_sd_card
    + service ROM | label: mmc.dtb           | + parent | label: imx8mq_sd_card-mnt_pocket.dtb
    + service ROM | label: usb               | + parent | label: imx8m_usb_host
    + service ROM | label: usb.dtb           | + parent | label: imx8m_usb_host-mnt_pocket.dtb
}

set driver_routes(pinephone) {
    + service ROM | label: mmc               | + parent | label: a64_sd_card
    + service ROM | label: mmc.dtb           | + parent | label: sd_card-pinephone.dtb
    + service ROM | label: fb                | + parent | label: de_fb
    + service ROM | label: fb.dtb            | + parent | label: de-pinephone.dtb
    + service ROM | label: touch             | + parent | label: goodix_touch
    + service ROM | label: touch.dtb         | + parent | label: goodix-pinephone.dtb
}

set driver_routes(imx8mp_armstone) {
    + service ROM | label: fb      | + parent | label: imx8mp_armstone_fb
    + service ROM | label: fb.dtb  | + parent | label: imx8mp_armstone_fb-imx8mp_armstone.dtb
    + service ROM | label: mmc     | + parent | label: imx8mq_sd_card
    + service ROM | label: mmc.dtb | + parent | label: imx8mq_sd_card-imx8mp_armstone.dtb
    + service ROM | label: usb     | + parent | label: imx8m_usb_host
    + service ROM | label: usb.dtb | + parent | label: imx8m_usb_host-imx8mp_armstone.dtb
}


##
# ROM routes that relabel generic driver names to platform-specific binaries
#
proc driver_routes { } {

	global driver_routes

	if {[info exists driver_routes([board])]} {
		return $driver_routes([board]); }

	return "";
}


install_config {
config | prio_levels: 2

+ parent-provides
  + service ROM
  + service IRQ
  + service IO_MEM
  + service IO_PORT
  + service PD
  + service RM
  + service CPU
  + service LOG
  + service TRACE
  + service VM

+ affinity-space | width: 2 | height: 1

+ default-route
  + any-service
    + parent
    + any-child
+ default | caps: 100 | ram: 1M

+ resource RAM | preserve: 2M

+ start timer | priority: 0
  + provides | + service Timer

+ start report_rom | priority: -1 | ram: 2M
  + provides
    + service Report
    + service ROM
  + config | verbose: no
    + policy | label: deploy -> blueprint | report: runtime -> blueprint
    + policy | label: runtime -> config   | report: deploy -> runtime
    + policy | label: runtime -> query    | report: deploy -> query
    + policy | label: report_fs -> init   | report: deploy -> runtime
    + policy | label: runtime -> state    | report: runtime -> state

+ start model_fs | caps: 200 | ram: 12M | priority: -1
  + binary vfs
  + provides | + service File_system
  + config
    + vfs
    | + dir orig | + tar model.tar
    | + ram
    | + import
    |   + tar model.tar
    + policy | label_prefix: ro -> | root: /
    + policy | label_prefix: rw -> | root: / | writeable: yes

+ start model_rom | ram: 10M | priority: -1
  + binary fs_rom
  + provides | + service ROM
  + route
    + service File_system | + child model_fs | identity: ro
    + any-service         | + parent

+ start terminal_monitor | ram: 2M | priority: -1
  + binary terminal_crosslink
  + provides | + service Terminal

+ start deploy
  + binary depot_deploy
  + route
    + service ROM | label: config           | + child model_rom | label: runtime
    + service ROM | label: deploy           | + child model_rom | label: deploy
    + service ROM | label: depot            | + child model_rom | label: depot/version
    + service ROM | label: blueprint        | + child report_rom
    + service ROM | label_prefix: option -> | + child model_rom | prepend_resource: option/
    + service Report                        | + child report_rom
    + any-service                           | + parent

+ start runtime | caps: 50000 | ram: 32G | priority: -1 | managing_system: yes
  + binary monitor
  + route
    + service ROM         | label: config          | + child report_rom
    + service ROM         | label: model_config    | + child model_rom | label: child/model
    + service ROM         | label: query           | + child report_rom
    + service ROM         | label: state           | + child report_rom
    + service ROM         | label: kernel_log      | + parent
    + service ROM         | label: core_log        | + parent
    + service Report      | label: state           | + child report_rom
    + service Report      | label: blueprint       | + child report_rom
    + service TRACE       | label: runtime         | + parent | label: runtime ->
    + service TRACE       | label: global          | + parent | label:
    + service File_system | label_prefix: model -> | + child model_fs | identity: rw
    + service Timer                                | + child timer
    } [driver_routes] {
    + service Terminal                             | + child terminal_monitor
    + any-service                                  | + parent
-
}


#
#

# directory structure
foreach subdir { option depot keyboard child } { file mkdir [model]/$subdir }

if {[llength [ingredients_of_type presets]] > 0} { file mkdir [model]/presets }

proc log_route { } {
	if {[log_core]} { return "parent" } else { return "child report" }
}

install_hid [model]/runtime {
config | arch: } [depot_spec] { | verbose: no | prio_levels: 8 | depot_rom: depot_rom
+ report  | init_ram: yes | init_caps: yes | child_ram: yes | child_caps: yes
          | requested: no | provided: no | delay_ms: 2000 | buffer: 1M
+ heartbeat | rate_ms: 2000
+ static
  + parent-provides
    + service ROM
    + service CPU
    + service PD
    + service RM
    + service LOG
    + service VM
    + service Timer
    + service Report
    + service File_system
    + service TRACE
    + service IO_MEM
    + service IO_PORT
    + service IRQ
    + service Terminal
+ common_routes
  + service ROM | label_last: ld.lib.so | + parent
  + service ROM | label_last: init      | + parent
  + service CPU                         | + parent
  + service PD                          | + parent
  + service LOG                         | + } [log_route] {
  + service Timer                       | + parent
-
}

# configs that are expected to be always present
set required_global_configs {
	deploy
	system
	manager
	fb
}

foreach config $required_global_configs {
	set ingredient [single_ingredient $config "default"]
	set from [ingredient_path $config $ingredient]
	set to   [model]/$config
	check_syntax $from
	copy_config $from $to
}

set required_child_configs {
	wifi
	event_filter
	font
	gui
	clipboard
	nic_router
	numlock_remap
	global_keys
	leitzentrale
	usb
	ram_fs
	report
	model
}

foreach config $required_child_configs {
	set ingredient [single_ingredient $config "default"]
	set from [ingredient_path $config $ingredient]
	set to   [model]/child/$config
	check_syntax $from
	copy_config $from $to
}

set from [ingredient_path platform [board]]
set to   [model]/child/platform
check_syntax $from
copy_config $from $to

# optional child configs that are managed by the sculpt manager if absent
set optional_configs {
	gpu
}

foreach config $optional_configs {
	set ingredient [single_ingredient $config ""]
	if {$ingredient != ""} {
		set from [ingredient_path $config $ingredient]
		set to   [model]/child/$config
		copy_config $from $to } }

##
# Return list of deploy files
#
proc deploy_files { } {

	set deploy_files [model]/deploy
	foreach preset [ingredients_of_type presets] {
		lappend deploy_files [ingredient_path deploy $preset] }
	return $deploy_files
}

##
# Return list of used deploy options
#
proc deploy_options { } {

	global _deploy_options

	if {[info exists _deploy_options]} { return $_deploy_options }

	# explicitely listed options
	lappend _deploy_options {*}[ingredients_of_type option]

	# gather options used in presets and deploy
	foreach path [deploy_files] {

		validate_hid [genode_dir]/repos/gems/src/app/depot_deploy/deploy.hsd $path

		set cmd [genode_dir]/tool/hid
		if {[looks_like_xml $path]} { lappend cmd --import-xml --output-xml }

		set names {}
		if {[catch {
			set names [split [exec {*}$cmd get "deploy | + option | : name" $path] "\n"]
			lappend _deploy_options {*}$names
		}]} {
			puts stderr "failed to parse $path for gathering deploy options"
			exit 1
		}
	}

	# remove duplicates
	set _deploy_options [lsort -unique $_deploy_options]

	foreach opt $_deploy_options {
		validate_hid [genode_dir]/repos/gems/src/app/depot_deploy/option.hsd \
		             [ingredient_path option $opt] }

	return $_deploy_options
}

# selection of depot users (pubkey and download files), options, and presets
foreach ingredient [ingredients_of_type depot] {
	set from [ingredient_path depot $ingredient]
	set to   [model]/depot/$ingredient
	copy_file $from $to }

foreach opt [deploy_options] {
	set from [ingredient_path option $opt]
	set to   [model]/option/$opt
	copy_config $from $to }

foreach ingredient [ingredients_of_type presets] {
	set from [ingredient_path deploy $ingredient]
	set to   [model]/presets/$ingredient
	copy_config $from $to }

copy_file [genode_dir]/repos/gems/recipes/pkg/sculpt/README [model]/README
copy_file [genode_dir]/repos/gems/run/sculpt/vimrc          [model]/vimrc

# keyboard layouts
foreach file { en_us de_ch de_de fr_ch fr_fr fr_bepo special } {
	set from [genode_dir]/repos/os/src/server/event_filter/$file.chargen
	set to   [model]/keyboard/$file
	check_syntax $from
	copy_config $from $to }

install_hid [model]/install "install | managed: yes | arch: [depot_spec]\n-"
install_hid [model]/child/depot_query     "query\n-"
install_hid [model]/child/blueprint_query "query\n-"
install_hid [model]/depot/version "depot | managed: yes | version: 1\n-"

# dummy kernel/core log ROMs for kernels w/o log-export feature
if {![have_spec nova]}  { install_hid [run_dir]/genode/kernel_log "" }
if {[have_board linux]} { install_hid [run_dir]/genode/core_log   "" }


#
# VERSION file at the root of the config fs, add newline for 'cat /VERSION'
#

set fd [open [model]/VERSION w]
puts $fd "[sculpt_version]"
close $fd

# supply VERSION as a boot module to the sculpt manager
file copy [model]/VERSION [run_dir]/genode/VERSION


#
# Generate build info as boot module
#

proc build_date { } { return [clock format [clock seconds] -format %Y-%m-%d] }

proc genode_version { } {

	if {[have_installed git] && [file exists [file join [genode_dir] .git]]} {
		return [exec [installed_command git] -C [genode_dir] describe \
		       {--dirty= <local changes>} 2> /dev/null] }

	set fh [open [file join [genode_dir] VERSION] "RDONLY"]
	set version [read $fh]
	close $fh

	regsub -all {\s} $version "" version
	return $version
}

set    build_info "build_info\n"
append build_info "  genode_version: [genode_version]\n"
append build_info "  date:           [build_date]\n"
append build_info "  depot_user:     [depot_user]\n"
append build_info "  arch:           [depot_spec]\n"
append build_info "  board:          $board_var\n"
append build_info "  base:           [depot_user]/bin/[depot_spec]/[base_src]/[_current_depot_archive_version src [base_src]]\n"
append build_info "-"

install_hid [run_dir]/genode/build_info $build_info


##
# Return list of 'pkg' attribute values found in 'type' nodes in an XML or HRD file
#
proc pkg_attribute_values { file node_path } {

	set cmd [genode_dir]/tool/hid
	if {[looks_like_xml $file]} { lappend cmd "--import-xml" }

	set result [split [exec {*}$cmd get "$node_path | : pkg" $file] "\n"]
	return $result
}


##
# Return list of pkg archives reference by the options and deploy config
#
proc referenced_pkg_values { } {

	set values {}

	# scan options
	foreach opt [deploy_options] {
		set path [model]/option/$opt
		lappend values {*}[pkg_attribute_values $path "option | + child"]
	}

	# scan presets
	foreach preset [ingredients_of_type presets] {
		set path [model]/presets/$preset
		lappend values {*}[pkg_attribute_values $path "config | + start"]
		lappend values {*}[pkg_attribute_values $path "deploy | + child"]
	}

	# scan deploy config
	lappend values {*}[pkg_attribute_values [model]/deploy "config | + start"]
	lappend values {*}[pkg_attribute_values [model]/deploy "deploy | + child"]

	return [lsort -unique $values]
}


#
# Replace pkg values of the form "name" by the form "user/pkg/name" suitable as
# arguments for '_collect_from_depot'.
#
proc pkg_archive_paths { values } {

	set result {}
	foreach value $values {
		if {[regexp {/} $value dummy]} {
			lappend result $value
		} else {
			lappend result "[depot_user]/pkg/$value"
		}
	}
	return $result
}


##
# Return which kind of depot archive is wanted: 'tar', 'omit', or 'list'
#
# tar  - includes the depot content referenced by the deploy configuration as
#        tar archive named 'depot.tar'
#
# omit - skips the evaluation of the deploy configuration
#
# list - outputs the list of packages needed for the deployment, which can
#        taken as input for manually publishing those packages
#
proc depot_archive { } {

	global ::env

	set archive "tar"
	if {[info exists ::env(DEPOT)]} {
		set archive "$::env(DEPOT)" }

	if {$archive != "omit" && $archive != "tar" && $archive != "list"} {
		puts stderr "Error: invalid value of DEPOT=$archive variable!" }

	return $archive
}


#
# Trigger the creation / updating of referenced depot content
#
# This step may update pkg versions if '--depot-auto-update' is enabled.
#
if {[depot_archive] == "tar" || [depot_archive] == "list"} {
	_collect_from_depot [pkg_archive_paths [referenced_pkg_values]]
}


#
# Augment deploy config and option files with current package versions
#

proc current_pkg { pkg } { return $pkg/[_current_depot_archive_version pkg $pkg] }


proc versioned_pkg { pkg } {

	if {[regexp [_depot_archive_versioned_path_pattern] $pkg dummy user type] && $type == "pkg"} {
		return $pkg
	} elseif {[regexp [_depot_archive_path_pattern] $pkg dummy user type name] && $type == "pkg"} {
		return $user/pkg/[current_pkg $name]
	} elseif {![regexp {/} $pkg dummy]} {
		return [depot_user]/pkg/[current_pkg $pkg]
	} else {
		puts stderr "Error: malformed depot-archive path '$pkg',"
		puts stderr "       expected '<user>/pkg/<name>' or"
		puts stderr "                '<name>' or"
		puts stderr "                '<user>/pkg/<name>/<version>'"
		exit
	}
}


proc augment_child_node_pkg_versions { toplevel path } {

	set cmd [genode_dir]/tool/hid
	if {[looks_like_xml $path]} { lappend cmd --import-xml --output-xml }

	if {[catch {
		set names [split [exec {*}$cmd get "$toplevel | + child | : name" $path] "\n"]

		foreach name $names {
			set pkg [exec {*}$cmd get "$toplevel | + child $name | : pkg" $path]
			if {$pkg != ""} { # skip children deployed from ROM
				exec {*}$cmd -i set "$toplevel | + child $name | : pkg: [versioned_pkg $pkg]" $path
			}
		}
	}]} {
		puts stderr "failed to parse $path for augmenting pkg versions"
		exit
	}
}


proc augment_start_node_pkg_versions { path } {

	set cmd [genode_dir]/tool/hid
	if {[looks_like_xml $path]} { lappend cmd --import-xml --output-xml }

	if {[catch {
		set names [split [exec {*}$cmd get "config | + start | : name" $path] "\n"]

		foreach name $names {
			set pkg [exec {*}$cmd get "config | + start $name | : pkg" $path]
			exec {*}$cmd -i set "config | + start $name | : pkg: [versioned_pkg $pkg]" $path
		}
	}]} {
		puts stderr "failed to parse $path for augmenting pkg versions"
		exit
	}
}

# options
foreach opt [deploy_options] {
	augment_child_node_pkg_versions "option" [model]/option/$opt }

# presets
foreach preset [ingredients_of_type presets] {
	augment_child_node_pkg_versions "deploy" [model]/presets/$preset
	augment_start_node_pkg_versions          [model]/presets/$preset
}

# deploy config
augment_child_node_pkg_versions "deploy" [model]/deploy
augment_start_node_pkg_versions          [model]/deploy


##
## Depot content integrated in the Sculpt image
##

proc create_depot_archive { } {

	if {[depot_archive] == "tar"} {
		create_tar_from_depot_binaries [run_dir]/genode/depot.tar \
		                               {*}[pkg_archive_paths [referenced_pkg_values]]

	} else {
		create_tar_from_depot_binaries [run_dir]/genode/depot.tar
		if {[depot_archive] == "list"} {
			puts "Do not forget to publish:"
			puts [pkg_archive_paths [referenced_pkg_values]]
		}
	}
}

create_depot_archive


#
# Create model.tar to be mounted at the root of the model fs
#

exec sh -c "tar cf [run_dir]/genode/model.tar -C [model] ."

file delete -force [model]


##
## Auxiliary boot modules
##

#
# Linux-specific tweaks
#
if {[have_board linux]} {

	#
	# The Linux version of core does not export a platform_info ROM module.
	#
	install_boot_module "platform_info" "platform\n-\n"
}


# support for the Leitzentrale GUI
copy_file [genode_dir]/repos/gems/src/app/backdrop/genode_logo.png [run_dir]/genode/
copy_file [genode_dir]/repos/gems/run/sculpt/drop_shadow.png       [run_dir]/genode/


#
# Generate depot index from gems/run/sculpt/index
#

set fd [open [genode_dir]/repos/gems/run/sculpt/index r]
set pkg_index [read $fd]
close $fd

# filter 'pkg' attribute
set pattern { pkg [|] path: ([^/ |]+) }
while {[regexp $pattern $pkg_index dummy pkg]} {
	set pkg_path [depot_user]/pkg/[current_pkg $pkg]
	regsub $pattern $pkg_index " pkg | path: $pkg_path " pkg_index
}

# write filtered pkg index into the depot
file mkdir [depot_dir]/[depot_user]/index
set fd [open [depot_dir]/[depot_user]/index/[sculpt_version] w]
puts $fd $pkg_index
close $fd


##
## Create boot image
##

build [ingredients_of_type build]

append boot_modules [build_artifacts]

build_boot_image $boot_modules
