create_boot_directory

import_from_depot genodelabs/src/[base_src] \
                  genodelabs/pkg/[drivers_interactive_pkg] \
                  genodelabs/pkg/terminal \
                  genodelabs/src/init

install_config {
	<config>
		<parent-provides>
			<service name="ROM"/>
			<service name="LOG"/>
			<service name="RM"/>
			<service name="CPU"/>
			<service name="PD"/>
			<service name="IRQ"/>
			<service name="IO_PORT"/>
			<service name="IO_MEM"/>
		</parent-provides>

		<default-route>
			<any-service> <parent/> <any-child/> </any-service>
		</default-route>

		<default caps="100"/>

		<start name="timer">
			<resource name="RAM" quantum="1M"/>
			<provides><service name="Timer"/></provides>
		</start>

		<start name="drivers" caps="1000">
			<resource name="RAM" quantum="32M" constrain_phys="yes"/>
			<binary name="init"/>
			<route>
				<service name="ROM" label="config"> <parent label="drivers.config"/> </service>
				<service name="Timer"> <child name="timer"/> </service>
				<any-service> <parent/> </any-service>
			</route>
			<provides>
				<service name="Input"/> <service name="Framebuffer"/>
			</provides>
		</start>

		<start name="terminal">
			<resource name="RAM" quantum="2M"/>
			<provides><service name="Terminal"/></provides>
			<route>
				<service name="ROM" label="config"> <parent label="terminal.config"/> </service>
				<any-service> <parent/> <any-child/> </any-service>
			</route>
		</start>

		<start name="test-terminal_echo">
			<resource name="RAM" quantum="1M"/>
		</start>
	</config>
}

build { server/terminal test/terminal_echo }

build_boot_image { terminal test-terminal_echo }

run_genode_until forever

