create_boot_directory

import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/pkg/[drivers_interactive_pkg] \
                  [depot_user]/pkg/terminal \
                  [depot_user]/src/nitpicker \
                  [depot_user]/src/init \
                  [depot_user]/src/test-terminal_echo

install_config {
	<config>
		<parent-provides>
			<service name="ROM"/>
			<service name="LOG"/>
			<service name="RM"/>
			<service name="CPU"/>
			<service name="PD"/>
			<service name="IRQ"/>
			<service name="IO_PORT"/>
			<service name="IO_MEM"/>
		</parent-provides>

		<default-route>
			<any-service> <parent/> <any-child/> </any-service>
		</default-route>

		<default caps="100"/>

		<start name="timer">
			<resource name="RAM" quantum="1M"/>
			<provides><service name="Timer"/></provides>
		</start>

		<start name="drivers" caps="1500" managing_system="yes">
			<resource name="RAM" quantum="64M"/>
			<binary name="init"/>
			<route>
				<service name="ROM" label="config"> <parent label="drivers.config"/> </service>
				<service name="Timer"> <child name="timer"/> </service>
				<service name="Capture"> <child name="nitpicker"/> </service>
				<service name="Event">   <child name="nitpicker"/> </service>
				<any-service> <parent/> </any-service>
			</route>
		</start>

		<start name="nitpicker">
			<resource name="RAM" quantum="4M"/>
			<provides>
				<service name="Gui"/> <service name="Capture"/> <service name="Event"/>
			</provides>
			<config focus="rom">
				<capture/> <event/>
				<domain name="default" layer="2" content="client" label="no" hover="always"/>
				<default-policy domain="default"/>
			</config>
		</start>

		<start name="terminal" caps="110">
			<resource name="RAM" quantum="6M"/>
			<provides><service name="Terminal"/></provides>
			<route>
				<service name="ROM" label="config"> <parent label="terminal.config"/> </service>
				<service name="Gui"> <child name="nitpicker" label="terminal"/> </service>
				<any-service> <parent/> <any-child/> </any-service>
			</route>
		</start>

		<start name="test-terminal_echo">
			<resource name="RAM" quantum="1M"/>
		</start>
	</config>
}

set fd [open [run_dir]/genode/focus w]
puts $fd "<focus label=\"terminal\" domain=\"default\"/>"
close $fd

build { server/terminal }

build_boot_image { terminal }

run_genode_until forever

