create_boot_directory

import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/pkg/[drivers_interactive_pkg] \
                  [depot_user]/pkg/terminal \
                  [depot_user]/src/nitpicker \
                  [depot_user]/src/init \
                  [depot_user]/src/test-terminal_echo

install_config {
config
+ parent-provides
  + service ROM
  + service LOG
  + service RM
  + service CPU
  + service PD
  + service IRQ
  + service IO_PORT
  + service IO_MEM

+ default-route
  + any-service
    + parent
    + any-child

+ default | caps: 100 | ram: 1M

+ start timer
  + provides | + service Timer

+ start drivers | caps: 1500 | ram: 64M | managing_system: yes
  + binary init
  + route
    + service ROM | label: config | + parent | label: drivers.config
    + service Timer               | + child timer
    + service Capture             | + child nitpicker
    + service Event               | + child nitpicker
    + any-service                 | + parent

+ start nitpicker | ram: 4M
  + provides
    + service Gui
    + service Capture
    + service Event
  + config | focus: rom
    + capture
    + event
    + domain default | layer: 2 | content: client | label: no | hover: always
    + default-policy | domain: default

+ start terminal | caps: 110 | ram: 6M
  + provides | + service Terminal
  + route
    + service ROM | label: config | + parent          | label: terminal.config
    + service Gui                 | + child nitpicker | label: terminal
    + any-service
      + parent
      + any-child

+ start test-terminal_echo
-
}

set fd [open [run_dir]/genode/focus w]
puts $fd "focus | label: terminal | domain: default\n-"
close $fd

build { server/terminal }

build_boot_image [build_artifacts]

run_genode_until forever

