#
# \brief  Showcases terminal_log server
# \author Stefan Kalkowski
# \date   2012-05-21
#

set build_components {
	core
	init
	drivers/framebuffer
	drivers/input
	drivers/timer
	server/nitpicker
	server/nit_fb
	server/terminal
	server/terminal_log
	test/nitpicker
	app/launchpad
	app/pointer
}

source ${genode_dir}/repos/base/run/platform_drv.inc
append_platform_drv_build_components

build $build_components

create_boot_directory

append config {
<config>
	<parent-provides>
		<service name="ROM"/>
		<service name="RAM"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="LOG"/>
	</parent-provides>
	<default-route>
		<service name="Nitpicker"> <child name="nitpicker"/> </service>
		<service name="Timer">     <child name="timer"/> </service>
		<service name="Terminal">  <child name="terminal"/> </service>
		<service name="Platform">  <child name="platform_drv"/> </service>
		<any-service><parent/></any-service>
	</default-route>
	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Timer"/></provides>
	</start>
}

append_if [have_spec sdl] config {
	<start name="fb_sdl">
		<resource name="RAM" quantum="4M"/>
		<provides>
			<service name="Input"/>
			<service name="Framebuffer"/>
		</provides>
	</start>
	<alias name="fb_drv"    child="fb_sdl"/>
	<alias name="input_drv" child="fb_sdl"/>}

append_platform_drv_config

append_if [have_spec framebuffer] config {
	<start name="fb_drv">
		<resource name="RAM" quantum="4M"/>
		<provides><service name="Framebuffer"/></provides>
	</start>}

append_if [have_spec ps2] config {
	<start name="ps2_drv">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Input"/></provides>
	</start>
	<alias name="input_drv" child="ps2_drv"/>}

append config {
	<start name="nitpicker">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Nitpicker"/></provides>
		<config>
			<domain name="pointer" layer="1" content="client" label="no" origin="pointer" />
			<domain name="default" layer="2" content="client" label="no" focus="click" hover="always" />
			<policy label_prefix="pointer" domain="pointer"/>
			<default-policy domain="default"/>
		</config>
		<route>
			<service name="Input">       <child name="input_drv"/> </service>
			<service name="Framebuffer"> <child name="fb_drv"/>    </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>
	<start name="pointer">
		<resource name="RAM" quantum="1M"/>
	</start>
	<start name="terminal_fb">
		<binary name="nit_fb"/>
		<resource name="RAM" quantum="4M"/>
		<provides>
			<service name="Framebuffer"/>
			<service name="Input"/>
		</provides>
		<config xpos="0" ypos="0" width="640" height="480" refresh_rate="25"/>
	</start>
	<start name="terminal">
		<resource name="RAM" quantum="3M"/>
		<provides><service name="Terminal"/></provides>
		<route>
			<service name="Input">       <child name="terminal_fb"/> </service>
			<service name="Framebuffer"> <child name="terminal_fb"/> </service>
			<any-service> <parent/> <any-child/></any-service>
		</route>
	</start>
	<start name="terminal_log">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="LOG"/></provides>
	</start>
	<start name="launchpad">
		<resource name="RAM" quantum="32M"/>
		<route>
			<service name="LOG">       <child name="terminal_log"/> </service>
			<any-service> <any-child/> <parent/></any-service>
		</route>
		<config>
			<launcher name="testnit"   ram_quota="768K" />
		</config>
	</start>
</config>
}
install_config $config

# generic modules
set boot_modules {
	core ld.lib.so init
	timer
	nitpicker
	pointer
	launchpad
	testnit
	nit_fb
	terminal
	terminal_log
}

# platform-specific modules
lappend_if [have_spec       linux] boot_modules fb_sdl
lappend_if [have_spec framebuffer] boot_modules fb_drv
lappend_if [have_spec         ps2] boot_modules ps2_drv

append_platform_drv_boot_modules

build_boot_image $boot_modules

append qemu_args " -m 256 "
run_genode_until forever
