create_boot_directory

import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/pkg/[drivers_interactive_pkg] \
                  [depot_user]/pkg/fonts_fs \
                  [depot_user]/src/init \
                  [depot_user]/src/report_rom \
                  [depot_user]/src/nitpicker \
                  [depot_user]/src/libc \
                  [depot_user]/src/libpng \
                  [depot_user]/src/zlib \
                  [depot_user]/src/vfs_import

install_config {
config
+ parent-provides
  + service PD
  + service CPU
  + service ROM
  + service RM
  + service LOG
  + service IRQ
  + service IO_MEM
  + service IO_PORT

+ default | caps: 100 | ram: 1M

+ default-route
  + any-service
    + parent
    + any-child

+ start timer
  + provides | + service Timer

+ start drivers | caps: 1500 | ram: 64M | managing_system: yes
  + binary init
  + route
    + service ROM | label: config | + parent | label: drivers.config
    + service Timer               | + child timer
    + service Capture             | + child nitpicker
    + service Event               | + child nitpicker
    + any-service                 | + parent

+ start report_rom
  + provides
    + service Report
    + service ROM
  + config | verbose: yes
    + policy | label:  text_area.1 -> hover     | report: nitpicker -> hover
    + policy | label:  text_area.2 -> clipboard | report: text_area.2 -> clipboard

+ start nitpicker | ram: 4M
  + provides
    + service Gui
    + service Capture
    + service Event
  + config | focus: rom
    + capture
    + event
    + report | hover: yes
    + background | color: #123456
    + domain pointer | layer: 1 | content: client | label: no | origin: pointer
    + domain default | layer: 3 | content: client | label: no | hover: always
    + domain second  | layer: 2 | content: client | label: no | hover: always
                     | xpos: 200 | ypos: 300
    + policy | label_prefix: pointer     | domain: pointer
    + policy | label_prefix: text_area.2 | domain: second
    + default-policy                     | domain: default

+ start pointer
  + route
    + service Gui | + child nitpicker
    + any-service
      + parent
      + any-child

+ start fonts_fs | caps: 300 | ram: 8M
  + binary vfs
  + provides | + service File_system
  + route
    + service ROM | label: config | + parent | label: fonts_fs.config
    + any-service                 | + parent

+ start data_fs | caps: 300 | ram: 8M
  + binary vfs
  + provides | + service File_system
  + config
  | + vfs
  |   + ram
  |   + import
  |     + rom drivers.config | binary: no
  | + default-policy | root: / | writeable: yes
  + route | + any-service | + parent

+ start text_area.1 | caps: 250 | ram: 8M
  + binary text_area
  + config
  |        path:       /data/drivers.config
  |        max_lines:  20
  |        min_width:  500
  |        min_height: 300
  |        watch:      yes
  |
  | + vfs | + dir data | + fs | label: data -> /
  + route
    + service ROM | label: hover                   | + child report_rom
    + service File_system | label_prefix: fonts -> | + child fonts_fs
    + service File_system | label_prefix: data ->  | + child data_fs
    + any-service
      + parent
      + any-child

+ start text_area.2 | caps: 250 | ram: 8M
  + binary text_area
  + config
  |        path:      /data/drivers.config
  |        copy:      yes
  |        paste:     yes
  |        max_lines: 10
  |        min_width: 600
  |
  | + report | saved: yes
  | + save | version: 1
  | + vfs | + dir data | + fs | label: data -> /
  + route
    + service Report                               | + child report_rom
    + service ROM | label: clipboard               | + child report_rom
    + service File_system | label_prefix: fonts -> | + child fonts_fs
    + service File_system | label_prefix: data ->  | + child data_fs
    + any-service
      + parent
      + any-child
-
}

set fd [open [run_dir]/genode/focus w]
puts $fd "focus | label: text_area.2 ->\n-"
close $fd

build { app/text_area app/menu_view lib/vfs lib/sandbox lib/dialog }

build_boot_image [build_artifacts]

run_genode_until forever
