create_boot_directory

import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/pkg/[drivers_interactive_pkg] \
                  [depot_user]/pkg/fonts_fs \
                  [depot_user]/src/init \
                  [depot_user]/src/report_rom \
                  [depot_user]/src/nitpicker \
                  [depot_user]/src/libc \
                  [depot_user]/src/libpng \
                  [depot_user]/src/zlib \
                  [depot_user]/src/vfs_import

install_config {
<config>
	<parent-provides>
		<service name="PD"/>
		<service name="CPU"/>
		<service name="ROM"/>
		<service name="RM"/>
		<service name="LOG"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
	</parent-provides>

	<default caps="100"/>

	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Timer"/></provides>
	</start>

	<start name="drivers" caps="1000">
		<resource name="RAM" quantum="32M" constrain_phys="yes"/>
		<binary name="init"/>
		<route>
			<service name="ROM" label="config"> <parent label="drivers.config"/> </service>
			<service name="Timer"> <child name="timer"/> </service>
			<any-service> <parent/> </any-service>
		</route>
		<provides>
			<service name="Input"/> <service name="Framebuffer"/>
		</provides>
	</start>

	<start name="report_rom">
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Report"/> <service name="ROM"/> </provides>
		<config verbose="yes">
			<policy label="text_area.1 -> hover" report="nitpicker -> hover"/>
			<policy label="text_area.2 -> clipboard" report="text_area.2 -> clipboard"/>
		</config>
	</start>

	<start name="nitpicker">
		<resource name="RAM" quantum="4M"/>
		<provides><service name="Nitpicker"/></provides>
		<config focus="rom">
			<report hover="yes"/>
			<background color="#123456"/>
			<domain name="pointer" layer="1" content="client" label="no" origin="pointer" />
			<domain name="default" layer="3" content="client" label="no" hover="always" />
			<domain name="second" layer="2" xpos="200" ypos="300" content="client" label="no" hover="always" />

			<policy label_prefix="pointer" domain="pointer"/>
			<policy label_prefix="text_area.2" domain="second"/>
			<default-policy domain="default"/>
		</config>
	</start>

	<start name="pointer">
		<resource name="RAM" quantum="1M"/>
		<route>
			<service name="Nitpicker"> <child name="nitpicker" /> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

	<start name="fonts_fs" caps="300">
		<resource name="RAM" quantum="8M"/>
		<binary name="vfs"/>
		<route>
			<service name="ROM" label="config"> <parent label="fonts_fs.config"/> </service>
			<any-service> <parent/> </any-service>
		</route>
		<provides> <service name="File_system"/> </provides>
	</start>

	<start name="data_fs" caps="300">
		<resource name="RAM" quantum="8M"/>
		<binary name="vfs"/>
		<config>
			<vfs>
				<ram/>
				<import>
					<rom name="drivers.config" binary="no"/>
				</import>
			</vfs>
			<default-policy root="/" writeable="yes"/>
		</config>
		<route> <any-service> <parent/> </any-service> </route>
		<provides> <service name="File_system"/> </provides>
	</start>

	<start name="text_area.1" caps="250">
		<binary name="text_area"/>
		<resource name="RAM" quantum="8M"/>
		<config path="/data/drivers.config" max_lines="20" min_width="500" min_height="300" watch="yes">
			<vfs> <dir name="data"> <fs label="data"/> </dir> </vfs>
		</config>
		<route>
			<service name="ROM" label="hover"> <child name="report_rom"/> </service>
			<service name="File_system" label="fonts"> <child name="fonts_fs"/> </service>
			<service name="File_system" label="data">  <child name="data_fs"/> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

	<start name="text_area.2" caps="250">
		<binary name="text_area"/>
		<resource name="RAM" quantum="8M"/>
		<config path="/data/drivers.config" copy="yes" paste="yes"
		        max_lines="10" min_width="600">
			<report saved="yes"/>
			<save version="1"/>
			<vfs> <dir name="data"> <fs label="data"/> </dir> </vfs>
		</config>
		<route>
			<service name="Report"> <child name="report_rom"/> </service>
			<service name="ROM" label="clipboard"> <child name="report_rom"/> </service>
			<service name="File_system" label="fonts"> <child name="fonts_fs"/> </service>
			<service name="File_system" label="data">  <child name="data_fs"/> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

</config>}

set fd [open [run_dir]/genode/focus w]
puts $fd "<focus label=\"text_area.2 -> \"/>"
close $fd

build { app/text_area app/menu_view }

build_boot_image { text_area sandbox.lib.so vfs.lib.so menu_view menu_view_styles.tar }

run_genode_until forever
