source ${genode_dir}/repos/libports/run/qt5_common.inc

import_from_depot [depot_user]/src/qt5_component \
                  [depot_user]/src/qt5_textedit \
                  [depot_user]/src/dynamic_rom \
                  [depot_user]/src/test-tiled_wm

#
# Generate config
#

proc qt5_layouter_config { } {
	return {+ config | rules: rom | + report | rules: no }
}

proc qt5_decorator_binary { } { return "themed_decorator" }

proc qt5_decorator_config { } {
	return {
  + config
    + vfs
      + dir theme
        + inline metadata
          + theme
            + aura  | top: 0 | bottom: 0 | left: 0 | right: 0
            + decor | top: 0 | bottom: 0 | left: 0 | right: 0
    + libc
    + default-policy
    }
}

install_config {
config
+ parent-provides
  } [qt5_parent_provides] {
+ default | caps: 100 | ram: 1M
+ default-route
  + any-service
    + parent
    + any-child
} [qt5_start_nodes] {

+ start test_reports
  + binary report_rom
  + provides
    + service Report
    + service ROM
  + config | verbose: no
    + policy | label: test-tiled_wm-panel -> apps              | report: test-tiled_wm-manager -> apps
    + policy | label: test-tiled_wm-panel -> overlay           | report: test-tiled_wm-manager -> overlay
    + policy | label: test-tiled_wm-manager -> content_request | report: test-tiled_wm-panel -> content_request
    + policy | label: test-tiled_wm-manager -> overlay_request | report: test-tiled_wm-panel -> overlay_request

+ start wifi_reports | ram: 4M
  + binary dynamic_rom
  + provides | + service ROM
  + config | verbose: no
    + rom accesspoints
      + inline
        + accesspoints
          + accesspoint | ssid: skynet | bssid: 00:01:02:03:04:05 | quality: 40
          + accesspoint | ssid: foobar | bssid: 01:02:03:04:05:06 | quality: 70 | protection: WPA2
          + accesspoint | ssid: foobar | bssid: 01:02:03:04:05:07 | quality: 10 | protection: WPA2
      + sleep | milliseconds: 60000
      + inline
        + accesspoints
      + sleep | milliseconds: 60000
    + rom state
      + inline
        + state
          + accesspoint | ssid: foobar | bssid: 01:02:03:04:05:06 | quality: 70 | freq: 2418 | state: disconnected
      + sleep | milliseconds: 60000
      + inline
        + state
          + accesspoint | ssid: foobar | bssid: 01:02:03:04:05:06 | quality: 70 | freq: 2418 | state: connecting
      + sleep | milliseconds: 60000

+ start test-tiled_wm-manager | caps: 120 | ram: 8M
  + route
    + service ROM    | label: content_request | + child test_reports
    + service ROM    | label: overlay_request | + child test_reports
    + service Report | label: layout_rules    | + child wm_report_rom | label: layout_rules
    + service Report                          | + child test_reports
    + any-service
      + parent
      + any-child

+ start test-tiled_wm-panel | caps: 250 | ram: 32M
  + config
    + libc | stdout: /dev/log | stderr: /dev/log | pipe: /pipe | rtc: /dev/rtc
    + vfs
      + dir dev
        + log
        + inline rtc | : 2018-01-01 00:01
      + dir pipe | + pipe
      + dir fs   | + ram
      + tar qt5_dejavusans.tar
      + tar qt5_libqgenode.tar
  + route
    + service Gui                             | + child wm
    + service Report | label: shape           | + child wm
    + service ROM    | label: mesa_gpu.lib.so | + parent             | label: mesa_gpu-softpipe.lib.so
    + service ROM    | label: apps            | + child test_reports
    + service ROM    | label: overlay         | + child test_reports
    + service Report                          | + child test_reports
    + any-service
      + parent
      + any-child

+ start test-tiled_wm-overlay | caps: 250 | ram: 32M
  + config
    + libc | stdout: /dev/log | stderr: /dev/log | pipe: /pipe | rtc: /dev/rtc
    + vfs
      + dir dev
        + log
        + inline rtc | : 2018-01-01 00:01
      + dir pipe | + pipe
      + dir fs   | + ram
      + tar qt5_dejavusans.tar
      + tar qt5_libqgenode.tar
  + route
    + service Gui                             | + child wm
    + service Report | label: shape           | + child wm
    + service ROM    | label: mesa_gpu.lib.so | + parent   | label: mesa_gpu-softpipe.lib.so
    + any-service
      + parent
      + any-child

+ start test-tiled_wm-app-1 | caps: 250 | ram: 32M
  + binary test-tiled_wm-app
  + config app1
    + libc | stdout: /dev/log | stderr: /dev/log | pipe: /pipe | rtc: /dev/rtc
    + vfs
      + dir dev
        + log
        + inline rtc | : 2018-01-01 00:01
      + dir pipe | + pipe
      + dir fs   | + ram
      + tar qt5_dejavusans.tar
      + tar qt5_libqgenode.tar
  + route
    + service Gui                             | + child wm
    + service Report | label: shape           | + child wm
    + service ROM    | label: mesa_gpu.lib.so | + parent   | label: mesa_gpu-softpipe.lib.so
    + any-service
      + parent
      + any-child

+ start test-tiled_wm-app-2 | caps: 250 | ram: 32M
  + binary test-tiled_wm-app
  + config app2
    + libc | stdout: /dev/log | stderr: /dev/log | pipe: /pipe | rtc: /dev/rtc
    + vfs
      + dir dev
        + log
        + inline rtc | : 2018-01-01 00:01
      + dir pipe | + pipe
      + dir fs   | + ram
      + tar qt5_dejavusans.tar
      + tar qt5_libqgenode.tar
  + route
    + service Gui                             | + child wm
    + service Report | label: shape           | + child wm
    + service ROM    | label: mesa_gpu.lib.so | + parent   | label: mesa_gpu-softpipe.lib.so
    + any-service
      + parent
      + any-child

+ start textedit | caps: 350 | ram: 70M
  + config
    + libc | stdout: /dev/log | stderr: /dev/log | pipe: /pipe | rtc: /dev/rtc
    + vfs
      + dir dev
        + log
        + inline rtc | : 2018-01-01 00:01
      + dir pipe | + pipe
      + dir fs   | + ram
      + tar qt5_dejavusans.tar
      + tar qt5_libqgenode.tar
  + route
    + service Gui                             | + child wm
    + service Report | label: shape           | + child wm
    + service ROM    | label: mesa_gpu.lib.so | + parent   | label: mesa_gpu-softpipe.lib.so
    + any-service
      + parent
      + any-child
-
}

build_boot_image [qt5_boot_modules]

append qemu_args " -device nec-usb-xhci,id=xhci -device usb-tablet"

run_genode_until forever

# vi: set ft=tcl :
