create_boot_directory

install_config {
	<config>

		<parent-provides>
			<service name="ROM"/>
			<service name="LOG"/>
			<service name="RM"/>
			<service name="CPU"/>
			<service name="PD"/>
			<service name="IRQ"/>
			<service name="IO_MEM"/>
			<service name="IO_PORT"/>
		</parent-provides>
		<default-route>
			<any-service> <parent/> <any-child/> </any-service>
		</default-route>
		<default caps="100"/>

		<start name="report_rom">
			<resource name="RAM" quantum="1M"/>
			<provides> <service name="Report"/> <service name="ROM"/> </provides>
			<config verbose="yes"/>
		</start>

		<start name="fs_query" caps="120">
			<resource name="RAM" quantum="2M"/>
			<config>
				<vfs>
					<inline name="x">Some file content!</inline>
				</vfs>
				<query path="/" content="yes" size="yes"/>
			</config>
		</start>

	</config>
}

append qemu_args " -nographic "

build { core init server/report_rom app/fs_query }

build_boot_image { core ld.lib.so init report_rom fs_query vfs.lib.so }

run_genode_until "</listing>.*\n" 30
