create_boot_directory

install_config {
	<config>

		<parent-provides>
			<service name="CPU"/>
			<service name="IO_MEM"/>
			<service name="IO_PORT"/>
			<service name="IRQ"/>
			<service name="LOG"/>
			<service name="PD"/>
			<service name="RM"/>
			<service name="ROM"/>
		</parent-provides>
		<default-route>
			<any-service> <parent/> <any-child/> </any-service>
		</default-route>
		<default caps="200"/>

		<start name="timer">
			<resource name="RAM" quantum="1M"/>
			<provides> <service name="Timer"/> </provides>
		</start>

		<start name="vfs_block">
			<resource name="RAM" quantum="68M" />
			<provides><service name="Block"/></provides>
			<config>
				<vfs>
					<ram/>
					<import>
						<rom name="disk_image_copy" label="disk_image"/>
					</import>
				</vfs>
				<policy label_prefix="vfs_example_5"
				        file="/disk_image_copy"
				        block_size="512"
				        writeable="yes"/>
			</config>
		</start>

		<start name="vfs_example_5">
			<resource name="RAM" quantum="2M"/>
			<config>
				<vfs>
					<dir name="my_notes"> <fatfs/> </dir>
					<dir name="dev"> <log/> </dir>
				</vfs>
				<libc stdout="/dev/log"/>
			</config>
		</start>

	</config>
}

set mkfs_cmd [installed_command mkfs.vfat]
if {[catch { exec which $mkfs_cmd } ]} {
	puts stderr "Error: $mkfs_cmd not installed, aborting test";
	exit }

set disk_image "bin/disk_image"
set cmd "dd if=/dev/zero of=$disk_image bs=1024 count=65536"
puts "creating disk image: $cmd"
catch { exec sh -c $cmd }

set cmd "$mkfs_cmd -F32 -nlibc_vfs $disk_image"
puts "formating disk: $cmd"
catch { exec sh -c $cmd }

build {
	core init timer app/vfs_example_5 server/vfs_block lib/vfs_fatfs
	lib/vfs_import }

build_boot_image {
	disk_image core ld.lib.so init timer vfs_example_5 vfs_block
	vfs_import.lib.so vfs.lib.so vfs_fatfs.lib.so libc.lib.so libm.lib.so
	posix.lib.so }

append qemu_args " -nographic "

run_genode_until "exited with exit value 0.*\n" 30

exec rm -f $disk_image
