include $(REP_DIR)/lib/import/import-qt_ui_tools.mk

SHARED_LIB = yes

# extracted from tools/designer/src/uitools/Makefile
QT_DEFINES += -DQFORMINTERNAL_NAMESPACE -DQT_DESIGNER_STATIC -DQT_FORMBUILDER_NO_SCRIPT -DQT_DESIGNER -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB

CC_OPT += -Wno-unused-but-set-variable

# extracted from src/script/Makefile
QT_SOURCES = \
         abstractformbuilder.cpp \
         formbuilder.cpp \
         ui4.cpp \
         properties.cpp \
         formbuilderextra.cpp \
         resourcebuilder.cpp \
         textbuilder.cpp \
         quiloader.cpp \
         moc_properties_p.cpp \
         moc_quiloader.cpp

# some source files need to be generated by moc from other source/header files before
# they get #included again by the original source file in the compiling stage

# source files generated from existing header files ("moc_%.cpp: %.h" rule in spec-qt4.mk)
# extracted from "compiler_moc_header_make_all" target
COMPILER_MOC_HEADER_MAKE_ALL_FILES = \
                                     moc_properties_p.cpp \
                                     moc_quiloader.cpp

# source files generated from existing source files ("%.moc: %.cpp" rule in spec-qt4.mk)
# extracted from "compiler_moc_source_make_all" rule
COMPILER_MOC_SOURCE_MAKE_ALL_FILES = \
                                     quiloader.moc

INC_DIR += $(REP_DIR)/src/lib/qt4/mkspecs/qws/genode-x86-g++ \
           $(REP_DIR)/include/qt4 \
           $(REP_DIR)/contrib/$(QT4)/include \
           $(REP_DIR)/include/qt4/QtCore \
           $(REP_DIR)/contrib/$(QT4)/include/QtCore \
           $(REP_DIR)/include/qt4/QtCore/private \
           $(REP_DIR)/contrib/$(QT4)/include/QtCore/private \
           $(REP_DIR)/include/qt4/QtXml \
           $(REP_DIR)/contrib/$(QT4)/include/QtXml \
           $(REP_DIR)/include/qt4/QtXml/private \
           $(REP_DIR)/contrib/$(QT4)/include/QtXml/private \
           $(REP_DIR)/src/lib/qt4/tools/designer/src/lib/uilib \
           $(REP_DIR)/contrib/$(QT4)/tools/designer/src/lib/uilib \
           $(REP_DIR)/contrib/$(QT4)/tools/designer/src/uitools \
           $(REP_DIR)/src/lib/qt4/src/corelib/global

LIBS += qt_core qt_gui qt_xml libc

vpath % $(REP_DIR)/include/qt4/QtUiTools
vpath % $(REP_DIR)/include/qt4/QtUiTools/private

vpath % $(REP_DIR)/src/lib/qt4/tools/designer/src/lib/uilib
vpath % $(REP_DIR)/src/lib/qt4/tools/designer/src/uitools

vpath % $(REP_DIR)/contrib/$(QT4)/tools/designer/src/lib/uilib
vpath % $(REP_DIR)/contrib/$(QT4)/tools/designer/src/uitools

include $(REP_DIR)/lib/mk/qt.mk
