#
# \brief  Download, and unpack the NOVA hypervisor.
# \author Stefan Kalkowski
# \author Alexander Boettcher
# \date   2012-06-04
#

VERBOSE ?= @
ECHO    := @echo

#
# Print help information by default
#
help::

prepare:
	$(VERBOSE)../../tool/ports/prepare_port nova

help::
	$(ECHO)
	$(ECHO) "Prepare the NOVA base repository"
	$(ECHO)
	$(ECHO) "--- available commands ---"
	$(ECHO) "prepare - checkout upstream source codes"
	$(ECHO) "clean   - remove upstream source codes"
	$(ECHO)

