#define HAVE_DECODER_LZMA2 1

#define HAVE_DLFCN_H      1
#define HAVE_FCNTL_H      1
#define HAVE_GETOPT_H     1
#define HAVE_GETOPT_LONG  1
#define HAVE_INTTYPES_H   1
#define HAVE_LIMITS_H     1
#define HAVE_MEMORY_H     1
#define HAVE_OPTRESET     1
#define HAVE_STDBOOL_H    1
#define HAVE_STDINT_H     1
#define HAVE_STDLIB_H     1
#define HAVE_STRINGS_H    1
#define HAVE_STRING_H     1
#define HAVE_SYS_ENDIAN_H 1
#define HAVE_SYS_PARAM_H  1
#define HAVE_SYS_STAT_H   1
#define HAVE_SYS_TIME_H   1
#define HAVE_SYS_TYPES_H  1
#define HAVE_UINTPTR_T    1
#define HAVE_UNISTD_H     1
#define STDC_HEADERS      1
#define MYTHREAD_POSIX    1
