obj-y                   += genode_serial.o
obj-y                   += genode_balloon.o
obj-$(CONFIG_RTC_CLASS) += genode_rtc.o
obj-$(CONFIG_FB)        += genode_fb.o
obj-$(CONFIG_BLOCK)     += genode_block.o
obj-$(CONFIG_NET)       += genode_net.o
