#define BUILD_REVISION "0"
#define BUILD_TIMESTAMP "<none>"
#define HAVE_DECL_STRERROR_R 1
#define HAVE_DLFCN_H 1
#define HAVE_GCC_ATTRIBUTE_ALIGNED 1
#define HAVE_INTMAX_T 1
#define HAVE_INTTYPES_H 1
#define HAVE_LONG_LONG_INT 1
#define HAVE_MEMORY_H 1
#define HAVE_MEMRCHR 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRERROR_R 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_SELECT_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UINTMAX_T 1
#define HAVE_UNISTD_H 1
#define HAVE_UNSIGNED_LONG_LONG_INT 1
#define HOST_TRIPLET_STRING "unknown-host-triplet"
#define PACKAGE "libgpg-error"
#define PACKAGE_NAME "libgpg-error"
#define PACKAGE_VERSION "1.27"
#define REPLACEMENT_FOR_OFF_T "long"
#define STDC_HEADERS 1
#define TIME_WITH_SYS_TIME 1
#define VERSION "1.27"
#define GPGRT_ENABLE_ES_MACROS 1
#define USE_POSIX_THREADS 1
